# Reconhecimento de entidades nomeadas

In [ ]:
#!pip install -U spacy
#!python -m spacy download pt_core_news_sm
#!python -m spacy download en_core_web_sm

In [ ]:
import zipfile
import spacy
import pt_core_news_sm
import en_core_web_sm
import pandas as pd
import random
from tqdm import tqdm
from spacy.training import Example

In [ ]:
with zipfile.ZipFile('/content/texts.zip', 'r') as f:
  print(*f.namelist(), sep='\n')

ADI2TJDFT.txt
adi3767.txt
Ag10000170733596001.txt
Ag10105170208398001.txt
AgAIRR11889820145030011.txt
AgCr10582160008758001.txt
AgRgSTJ1.txt
AgRgSTJ2.txt
AgRgTSE1.txt
AgRgTSE3.txt
AIAgRAgI6193ARAGUARIMG.txt
airr801422012.txt
AIRR3999520145020086.txt
AIRR15708820115050222.txt
AP00000794920137060006.txt
AP00001415620157010201.txt
AP00001441420167030203.txt
AP771420167080008PA.txt
CP32320177080008PA.txt
DespSEPLAGDF.txt
ED1STM.txt
ED1TJAC.txt
EDAgRgTSE2.txt
EDEDARR208420135040232.txt
EDRR1TST.txt
EEDRR9715120105020002.txt
ERR731004520105130003.txt
HC110260SP.txt
HC151914AgRES.txt
HC340624SP.txt
HC418951PR.txt
HC70000845920187000000.txt
lei11340.txt
Lei11788.txt
LoaDF2018.txt
Pet128TSE5.txt
Port77DF.txt
Rcl3495STJ.txt
REE5908TSE4.txt
REsp1583083RS.txt
RR474820145230056.txt
RR942006420095040028.txt
RR2574407120025020372.txt
TCU4687.txt
TSTRR16037920105200001.txt
AC1TCU.txt
AC1TJAC.txt
AC1TJMG.txt
AC2.txt
ACORDAOTCU25052016.txt

In [ ]:
with zipfile.ZipFile('/content/texts.zip', 'r') as f:
  with f.open('ADI2TJDFT.txt') as arq:
    texto = arq.read().decode('utf-8')

print(texto)

Órgão	:	Conselho Especial
Classe	:	ADI  Ação Direta de Inconstitucionalidade
N. Processo	:	2010002019357-4
Requerente(s)	:	PROCURADORA-GERAL DE JUSTIÇA DO DISTRITO FEDERAL E TERRITÓRIOS
Requerido(s)	:	PRESIDENTE DA CÂMARA LEGISLATIVA DO DISTRITO FEDERAL E OUTRO(S)
Relator 	:	Desembargador LÉCIO RESENDE
	EMENTA
AÇÃO DIRETA DE INCONSTITUCIONALIDADE. LEIS DISTRITAIS N.º 747/1994 E 2018/1998. LEI COMPLEMENTAR DISTRITAL N.º 380/2001. INCONSTITUCIONALIDADE FORMAL. LEI ORGÂNICA DO DISTRITO FEDERAL. OCUPAÇÃO DE ÁREA PÚBLICA. COMPETÊNCIA PRIVATIVA DO GOVERNADOR DO DISTRITO FEDERAL. AÇÃO JULGADA PROCEDENTE EM RAZÃO DO VÍCIO FORMAL. Tanto o Decreto n.º 10.829/87, quanto a Portaria n.º 314/92, do Instituto Brasileiro do Patrimônio Cultural  IBPC, hoje Instituto do Patrimônio Histórico e Artístico Nacional  IPHAN, conferem ao Governador do Distrito Federal competência privativa para iniciar o processo legislativo, quando se tratar o tema de uso e ocupação do solo em todo o território do Distrito Federal.


	ACÓRDÃO
Acordam os Desembargadores do Conselho Especial do Tribunal de Justiça do Distrito Federal e dos Territórios LÉCIO RESENDE  Relator, JOÃO MAIORISI  Vogal, ROMÃO C. OLIVEIRA  Vogal, DÁCIO VIEIRA  Vogal, SÉRGIO BITTENCOURT  Vogal, LECIR MANOEL DA LUZ  Vogal, CARMELITA BRASIL  Vogal, WALDIR LEÔNCIO LOPES JÚNIOR  Vogal, J.J. COSTA CARVALHO  Vogal, HUMBERTO ADJUTO ULHÔA  Vogal, NÍDIA CORRÊA LIMA  Vogal, ANA MARIA DUARTE AMARANTE BRITO  Vogal, CRUZ MACEDO  - Vogal, ROBERBAL CASEMIRO BELINATI  Vogal, SILVÂNIO BARBOSA DOS SANTOS  Vogal, OTÁVIO AUGUSTO  Vogal, sob a presidência do Desembargador OTÁVIO AUGUSTO, em proferir a seguinte decisão: JULGOU-SE PROCEDENTE A AÇÃO, POR MAIORIA, de acordo com a ata do julgamento e notas taquigráficas.
Brasília (DF), 17 de maio de 2011

Des. LÉCIO RESENDE
Relator



R E L A T Ó R I O

A PROCURADORA-GERAL DE JUSTIÇA DO DISTRITO FEDERAL E TERRITÓRIOS propõe Ação Direta de Inconstitucionalidade em face das Leis distritais n.º 747, de 23 de agosto de 1994, e 2.018, de 28 de julho de 1998, e da Lei Complementar distrital n.º 380, de 4 de abril de 2001, que tratam da ocupação de áreas públicas na Região Administrativa do Paranoá  RA VII, sob a alegação de afronta aos artigos 3º, item XI, 52, 100, itens VI e XXI, e 321, todos da Lei Orgânica do Distrito Federal  LODF.
Narra que as normas impugnadas padecem de inconstitucionalidade formal, em razão de disciplinarem matérias de iniciativa legislativa do Chefe do Poder Executivo, as quais não poderiam ter sido propostas por membros do Poder Legislativo, em afronta aos dispositivos acima aludidos.
Requer a procedência do pedido para declarar, em tese e com efeitos ex tunc e eficácia erga omnes, a inconstitucionalidade das Leis distritais n.º 747/1994 e 2.018/1998, bem como da Lei Complementar distrital n.º 380/2001.
Com a inicial vieram os documentos de fls. 11/15.
O Presidente da Câmara Legislativa do Distrito Federal, nas informações de fls. 21/25, afirma que as matérias tratadas nas leis distritais e na lei complementar impugnadas não estão incluídas no rol daquelas cuja iniciativa de lei é privativa do Governador do Distrito Federal, não havendo se falar em vício de iniciativa. Sustenta que é da Câmara distrital a competência para a matéria constante das leis acoimadas de inconstitucional, conforme previsto no art. 58, da LODF.
O Governador do Distrito Federal presta informações às fls. 27/30, nas quais concorda com o pedido de declaração de inconstitucionalidade das normas objurgadas, em virtude de serem formalmente inconstitucionais.
A manifestação do Procurador-Geral do Distrito Federal, às fls. 32/37, é no sentido de opinar pela procedência do pedido quanto à alegação de inconstitucionalidade formal das normas impugnadas.
Parecer Ministerial de fls. 39/43 oficiando pelo conhecimento da ação direta e pela procedência do pedido deduzido na inicial.
É o Relatório.


V O T O S

O Senhor Desembargador LÉCIO RESENDE  Relator
A PROCURADORA-GERAL DE JUSTIÇA DO DISTRITO FEDERAL E TERRITÓRIOS propõe Ação Direta de Inconstitucionalidade em face das Leis distritais n.º 747, de 23 de agosto de 1994, e 2.018, de 28 de julho de 1998, e da Lei Complementar distrital n.º 380, de 4 de abril de 2001, que tratam da ocupação de áreas públicas na Região Administrativa do Paranoá  RA VII.
Em síntese, aduz a requerente que as normas impugnadas padecem de inconstitucionalidade formal, em razão de disciplinarem matérias de iniciativa legislativa do Chefe do Poder Executivo, as quais não poderiam ter sido propostas por membros do Poder Legislativo, em afronta aos artigos 3º, item XI, 52, 100, itens VI e XXI, e 321, todos da Lei Orgânica do Distrito Federal  LODF.
Requer a procedência do pedido para declarar, em tese e com efeitos ex tunc e eficácia erga omnes, a inconstitucionalidade das citadas normas.
Preliminarmente, verifica-se claramente na inicial que, ao cotejar infringência à Lei Orgânica do Distrito Federal, a presente Ação Direta objetiva garantir os princípios expressos na Carta Magna, sendo certo que a via adequada para se discutir a inconstitucionalidade de lei é a Ação Direta de Inconstitucionalidade.
Conforme estipula a alínea “a” do item I do art. 102 da Carta Magna, as leis e os atos normativos federais ou estaduais podem ser objeto do controle abstrato de normas.
O art. 125, § 2º da Constituição Federal, assim dispõe:
“Art. 125  Os Estados organizarão sua justiça, observados os princípios estabelecidos nesta Constituição.
§ 1º (...)
§ 2º - Cabe aos Estados a instituição de representação de inconstitucionalidade de leis ou atos normativos estaduais ou municipais em face da Constituição estadual, vedada a atribuição da legitimação para agir a um único órgão.”

Ficou, assim, instituído o controle abstrato de normas no âmbito estadual.
Apesar das peculiaridades que marcam o Distrito Federal, a sua Lei Orgânica constitui instrumento normativo com a finalidade de regular, de modo subordinante e com primazia sobre o ordenamento positivo distrital, a vida político-institucional e jurídico-administrativa do Distrito Federal, entidade integrante da Federação brasileira.
Nesse sentido, manifestou-se o eminente Ministro CELSO DE MELLO, quando do seu voto na ADI nº 980-DF, verbis:
“A Lei Orgânica do Distrito Federal constitui instrumento normativo primário destinado a regular, de modo subordinante  e com inegável primazia sobre o ordenamento positivo distrital  a vida jurídico-administrativa e político-institucional dessa entidade integrante da Federação brasileira. Este ato representa, dentro do sistema positivo, o momento inaugural e fundante da ordem jurídica vigente no âmbito do Distrito Federal. Em uma palavra: A Lei Orgânica equivale, em força, autoridade e eficácia jurídicas, a um verdadeiro estatuto constitucional, essencialmente equiparável às Constituições promulgadas pelos Estados-membros.” (DJU de 13 de maio de 1994, p. 11.337)

Está, pois, caracterizada a possibilidade do controle da constitucionalidade de leis estaduais ou municipais, tendo como parâmetro a Lei Orgânica do Distrito Federal, pois a mesma equivale em força, autoridade e eficácia jurídicas a um verdadeiro estatuto constitucional, essencialmente equiparável às constituições promulgadas pelos Estados-membros.
Finalmente, o excelso Supremo Tribunal Federal, na ADI n.º 1405-6/DF, firmou o entendimento de que o Tribunal de Justiça do Distrito Federal e dos Territórios é competente para julgar as demandas que versem sobre violação, por lei local, da Lei Orgânica do Distrito Federal.
Admito, assim, o controle abstrato, quer seja através da Ação Direta de Inconstitucionalidade, quer seja pela Ação Declaratória de Constitucionalidade, pelo Tribunal de Justiça do Distrito Federal e dos Territórios, observados os limites impostos pela Carta Magna quanto ao objeto e ao parâmetro de controle.
Ressalte-se que o art. 103, item III, do Regimento Interno deste egrégio Tribunal de Justiça, legitima o Procurador-Geral de Justiça do Distrito Federal e Territórios à proposição da presente Ação Direta de Inconstitucionalidade.
Admito, pois, a presente ação e tenho como ente legitimado a propô-la a Excelentíssima Senhora PROCURADORA-GERAL DE JUSTIÇA DO DISTRITO FEDERAL E TERRITÓRIOS.
Passo ao exame do pedido deduzido na inicial.
As determinações constantes nas referidas Leis distritais, ora impugnadas, têm o seguinte teor:
“LEI Nº 747, DE 23 DE AGOSTO DE 1994
(Autor do Projeto: Deputado Salviano Guimarães)
Promulgação negada pelo Sr. Governador do Distrito Federal ao Projeto de Lei que Autoriza o Poder Executivo a ocupar a Zona de Expansão Urbana do Paranoá  7 ZEU 1.
Faço saber que a Câmara Legislativa do Distrito Federal aprovou e eu promulgo, na forma do § 6º do art. 74 da Lei Orgânica do Distrito Federal, a Lei nº 747, de 23 de agosto de 1994:
Art. 1º Fica o Poder Executivo autorizado a ocupar a Zona de Expansão Urbana 1 do Paranoá  7 ZEU 1, nos termos da Lei nº 353, de 18 de novembro de 1992, para a fixação dos moradores remanescentes da antiga Vila Paranoá, não contemplados no Programa de Assentamento da População de Baixa Renda.
Art. 2º O Poder Executivo procederá ao levantamento para identificar as famílias que deverão ser beneficiadas, nos termos do que estabelece o Decreto nº 11.208, de 17 de agosto de 1988, ouvida a Associação de Moradores do Paranoá.
Art. 3º A ocupação da Zona de Expansão Urbana 1 do Paranoá  7 ZEU 1 fica condicionada ao zoneamento da Área de Proteção Ambiental do Lago Paranoá.
Art. 4º O plano urbanístico deverá ser elaborado pelo Poder Executivo até 90 (noventa) dias, contados a partir da publicação desta Lei.
Art. 5º Esta Lei entra em vigor na data de sua publicação.
Art. 6º Revogam-se as disposições em contrário.”

“LEI Nº 2.018, DE 28 DE JULHO DE 1998
(Autoria do Projeto: Deputado José Edmar)
Destina área para a implementação do Complexo Vivencial e Esportivo do Paranoá, na Região Administrativa do Paranoá  RA VII.
Faço saber que a Câmara Legislativa do Distrito Federal aprovou, o Governador do Distrito Federal, nos termos do § 3º do art. 74 da Lei Orgânica do Distrito Federal, sancionou, e eu, Presidente da Câmara Legislativa do Distrito Federal, na forma do § 6º do mesmo artigo, promulgo a seguinte Lei:
Art. 1º Fica destinada área para a implementação do Complexo Vivencial e Esportivo do Paranoá, na Região Administrativa do Paranoá  RA VII, com a seguinte delimitação:
I  as Quadras 3 e 5, ao norte;
II  a rodovia DF 005, ao sul;
III  a via de acesso à rodovia DF 005, a leste;
IV  os limites da Região Administrativa do Paranoá, a oeste.
Art. 2º O Complexo Vivencial e Esportivo do Paranoá tem por finalidade principal a recreação e o lazer e é constituído de:
I  ginásio de esportes;
II  estádio de futebol com demarcação de pista para a prática de
atletismo;
III  piscinas;
IV  pista de cooper;
V  áreas de convivência.
Art. 3º A área especificada no art. 1º constará do Plano Diretor Local do Paranoá, segundo as diretrizes do Plano Diretor de Ordenamento Territorial do Distrito Federal  PDOT.
Art. 4º Esta Lei entra em vigor na data de sua publicação.
Art. 5º Revogam-se as disposições em contrário.”

“LEI COMPLEMENTAR Nº 380, DE 4 DE ABRIL DE 2001
(Autoria do Projeto: Deputado César Lacerda)
Dispõe sobre a permissão de uso da área que especifica, na Região Administrativa do Paranoá  RA VII.
O Presidente da Câmara Legislativa do Distrito Federal promulga, nos termos do § 6º do art. 74 da Lei Orgânica do Distrito Federal, a seguinte Lei Complementar, oriunda de Projeto vetado pelo Governador do Distrito Federal e mantido pela Câmara Legislativa do Distrito Federal:
Art. 1º Fica permitido o uso comercial de bens e a prestação de serviços em geral na área de 24.414m² (vinte e quatro mil, quatrocentos e quatorze metros quadrados), situada na Região Administrativa do Paranoá  RA VII, em conformidade com as seguintes especificações:
I  localização: DF-001  Estrada Parque Contorno  EPCT, km 12,8, na Região Administrativa do Paranoá  RA VII, tendo como perímetro a área que começa no marco cravado no canto da cerca, na divisa da faixa de domínio da Rodovia DF-001
EPCT; seguindo pela cerca na divisa da faixa de domínio da referida rodovia com o azimute de 158º32'42" e a distância de 137,24m (cento e trinta e sete metros e vinte e quatro centímetros); seguindo à esquerda pela cerca com o azimute de 68º32'42" e a distância de 148,75m (cento e quarenta e oito metros e setenta e cinco centímetros); seguindo à esquerda pela cerca com o azimute de 338º32'42" e a distância de 137,24m (cento e trinta e sete metros e vinte e quatro centímetros); seguindo novamente à esquerda pela cerca com o azimute de 284º32'42" e a distância de 148,75m (cento e quarenta e oito metros e setenta e cinco centímetros), chegando ao marco inicial;
II  usos permitidos: uso comercial, com atividades de comércio de bens e serviços em geral, com nível de incomodidade 1 e 2, conforme definido no Anexo II da Lei Complementar nº 90, de 11 de março de
1998.
Art. 2º Fica permitido para o projeto de parcelamento o uso misto, comércio e residência.
Art. 3º A Norma de Edificação, Uso e Gabarito  NGB a ser utilizada para efeito desta Lei Complementar é a mesma que vigora atualmente para toda a Região Administrativa do Paranoá  RA VII.
Art. 4º O Poder Executivo regulamentará esta Lei Complementar no prazo de sessenta dias.
Art. 5º Esta Lei Complementar entra em vigor na data de sua publicação.
Art. 6º Revogam-se as disposições em contrário.”

Para melhor análise da matéria, confiram-se os dispositivos da Lei Orgânica do Distrito Federal tido como violados:
“Art. 3º São objetivos prioritários do Distrito Federal:
(...)
XI - zelar pelo conjunto urbanístico de Brasília, tombado sob a inscrição n.º 532 do Livro do Tombo Histórico, respeitadas as definições e critérios constantes do Decreto n.º 10.829, de 2 de outubro de 1987, e da Portaria n.º 314, de 8 de outubro de 1992, do então Instituto Brasileiro do Patrimônio Cultural - IBPC, hoje Instituto do Patrimônio Histórico e Artístico Nacional - IPHAN. (Inciso incluído pela Emenda a Lei Orgânica n.º 12, de 12 de dezembro de 1996  DODF de 19.12.96)
Art. 52. Cabe ao Poder Executivo a administração dos bens do Distrito Federal, ressalvado à Câmara Legislativa administrar aqueles utilizados em seus serviços e sob sua guarda.
Art. 100. Compete privativamenteao Governador do Distrito Federal:
(...)
VI  iniciar o processo legislativo, na forma e nos casos previstos nesta Lei Orgânica.
(...)
XXI  delegar, por decreto, a qualquer autoridade do Executivo atribuições administrativas que não sejam de sua exclusiva competência;
Art. 321. É atribuição do Poder Executivo conduzir, no âmbito do processo de planejamento do Distrito Federal, as bases de discussão e elaboração dos planos diretores de ordenamento territorial e locais, bem como sua implementação.” (grifo nosso)

As leis distritais e a lei complementar distrital, ora impugnadas, de autoria de Deputados Distritais (fls. 12, 14 e 15), padecem do vício de iniciativa, por não ser da competência do Poder Legislativo local a iniciativa de projetos de lei que disponham sobre a ocupação e o uso do solo em todo o território do Distrito Federal.
A matéria em questão somente poderia ter sido deduzida por intermédio de projeto de lei iniciado pelo Chefe do Poder Executivo.
Tal discussão já restou pacificada nesta egrégia Corte, conforme se pode verificar das ementas abaixo transcritas, sempre no sentido de que compete, privativamente, ao Governador do Distrito Federal, a iniciativa de leis que disponham sobre o uso, a desafetação e a destinação dos bens públicos do Distrito Federal. Vejamos:
“AÇÃO DIRETA DE INCONSTITUCIONALIDADE. LEI COMPLEMENTAR Nº 85/98. PROJETO DE AUTORIA PARLAMENTAR. COLIDÊNCIA COM A LEI ORGÂNICA DO DISTRITO FEDERAL. RESERVA DE INICIATIVA. VÍCIO FORMAL DE INCONSTITUCIONALIDADE. COMPETÊNCIA PRIVATIVA DO GOVERNADOR DO DISTRITO FEDERAL PARA A PROPOSITURA DE LEIS QUE VERSEM SOBRE ALTERAÇÃO DE USO DE SOLO NO ÂMBITO DO DISTRITO FEDERAL.
Conforme precedentes deste Tribunal de Justiça, o Poder Legislativo não pode tomar a iniciativa de elaborar leis para baixar normas que versem sobre alteração de uso de solo no âmbito do Distrito Federal. Nesta seara, a iniciativa de leis é exclusiva do Governador do Distrito Federal, a teor do disposto nos artigos 3º, inciso XI, 52 e 100, inciso VI, da Lei Orgânica do Distrito Federal. Dessa forma, sendo de iniciativa parlamentar a elaboração da Lei Complementar nº 85/98, nesta ação impugnada, a Câmara Legislativa do Distrito Federal foi além de sua competência, evidenciando a existência de vício formal, diante da ofensa ao princípio da iniciativa do processo legislativo e da separação dos poderes. Portanto, a proclamação da inconstitucionalidade da Lei Complementar Distrital nº 85, de 13 de fevereiro de 1998, com efeitos ex tunc e eficácia erga omnes é medida que se impõe.” (ADI 2010002007992-9, Conselho Especial, Relator Desembargador NATANAEL CAETANO, julgado em 14/9/2010, DJ-e de 17/11/2010 p. 44) (grifo nosso)

“AÇÃO DIRETA DE INCONSTITUCIONALIDADE. LEIS COMPLEMENTARES DISTRITAIS Nº 27/97, 30/97, 31/97, 39/97, 118/98, 124/98, 155/98, 203/99, 280/00, 287/00, 312/00, 537/02, 569/02, 632/02, 637/02.ALTERAÇÃO DE USO/OCUPAÇÃO OU DESAFETAÇÃO DE ÁREAS PÚBLICAS. INICIATIVA. DEPUTADOS DISTRITAIS. INCONSTITUCIONALIDADE FORMAL. TEORIA DA MODULAÇÃO TEMPORAL. INAPLICABILIDADE.
A iniciativa para elaboração de leis que disponham sobre o uso, ocupação e desafetação do solo no Distrito Federal é exclusiva de seu Governador, conforme previsto na Lei Orgânica do Distrito Federal.
A modulação dos efeitos da declaração de inconstitucionalidade somente é possível por razões de segurança jurídica ou de excepcional interesse social, em conformidade com o que dispõe o art. 27 da Lei nº 9.868/99, inocorrentes na hipótese.” (ADI 2010002002050-8, Conselho Especial, Relator Desembargador SÉRGIO BITTENCOURT, julgado em 17/8/2010, DJ-e de 17/11/2010 p. 44) (grifo nosso)

“CONSTITUCIONAL E ADMINISTRATIVO. AÇÃO DIRETA DE INCONSTITUCIONALIDADE. LEI COMPLEMENTAR DISTRITAL Nº 788, DE 02/12/2008. DESAFETAÇÃO DE ÁREAS INTERSTICIAIS DAS QUADRAS RESIDENCIAIS DE BRAZLÂNDIA-DF (RA IV). INCONSTITUCIONALIDADE FORMAL. EMENDA PARLAMENTAR. OFENSA À LEI ORGÂNICA DO DISTRITO FEDERAL E AOS PRINCÍPIOS ADMINISTRATIVOS.
1. Reconhece-se o vício formal de inconstitucionalidade apontado na Lei Complementar distrital nº 788, de 02 de dezembro de 2008, que, ao dispor sobre a desafetação e a ocupação dos espaços intersticiais das quadras residenciais de Brazlândia-DF  Região Administrativa IV, não observou a legitimidade para a propositura de leis que versem sobre a administração de áreas públicas e sobre o uso e a ocupação do solo no Distrito Federal, que é privativa do Chefe do Poder Executivo local. Precedentes desta Corte.
2. Ação direta de inconstitucionalidade conhecida e julgada procedente.” (ADI 2009002013564-6, Conselho Especial, Relator Desembargador CRUZ MACEDO, julgado em 27/4/2010, DJ-e de 14/6/2010 p. 79) (grifo nosso)

Ressalte-se, ainda, que cabe ao Distrito Federal respeitar as definições e os critérios insertos no Decreto n.º 10.829/1987 e na Portaria n.º 314/1992, do Instituto Brasileiro do Patrimônio Histórico e Artístico Nacional  IPHAN, e de outro lado é competência privativa do Governador a iniciativa do processo legislativo a respeito do uso e ocupação do solo do Distrito Federal, sendo responsabilidade da Câmara Legislativa apenas a votação de tal projeto.
Vejamos a redação do artigo 3º, item XI, da Lei Orgânica do Distrito Federal, verbis:
“Art. 3º. São objetivos prioritários do Distrito Federal:
(...)

In [ ]:
model_ner = pt_core_news_sm.load()
doc = model_ner(texto)


entidades = []
labels = []

for ent in doc.ents:
  entidades.append(ent.text)
  labels.append(ent.label_)

pd.DataFrame({'entidade': entidades, 'label': labels})

                                        entidade label
0                                          Órgão   LOC
1                      Conselho Especial\nClasse   ORG
2    DISTRITO FEDERAL E TERRITÓRIOS\nRequerido(s   LOC
3                                      DA CÂMARA   ORG
4           DISTRITO FEDERAL E OUTRO(S)\nRelator   LOC
..                                           ...   ...
851                                   PROCEDENTE   LOC
852                              Leis Distritais  MISC
853                             Lei Complementar  MISC
854                                        omnes   ORG
855                                    D E C I S  MISC

[856 rows x 2 columns]

In [ ]:
model_ner.get_pipe('ner').labels

('LOC', 'MISC', 'ORG', 'PER')

In [ ]:
print('LOC', spacy.explain('LOC'))
print('PER', spacy.explain('PER'))
print('ORG', spacy.explain('ORG'))
print('MISC', spacy.explain('MISC'))

LOC Non-GPE locations, mountain ranges, bodies of water
PER Named person or family.
ORG Companies, agencies, institutions, etc.
MISC Miscellaneous entities, e.g. events, nationalities, products or works of art

In [ ]:
spacy.displacy.render(doc, style='ent', jupyter=True)

In [ ]:
import en_core_web_sm

model_ner_ing = spacy.load('en_core_web_sm')
model_ner_ing.get_pipe('ner').labels

('CARDINAL',
 'DATE',
 'EVENT',
 'FAC',
 'GPE',
 'LANGUAGE',
 'LAW',
 'LOC',
 'MONEY',
 'NORP',
 'ORDINAL',
 'ORG',
 'PERCENT',
 'PERSON',
 'PRODUCT',
 'QUANTITY',
 'TIME',
 'WORK_OF_ART')

In [ ]:
dados = []

with zipfile.ZipFile('/content/texts.zip') as f:
  for nome_arq in f.namelist():
    with f.open(nome_arq) as arquivo:
      conteudo = arquivo.read().decode('utf-8')
      palavras = conteudo.split()
      for palavra in palavras:
        dados.append([nome_arq, palavra])

tabela_palavras = pd.DataFrame(dados, columns = ['arquivo', 'palavra'])
tabela_palavras

                       arquivo              palavra
0                ADI2TJDFT.txt                Órgão
1                ADI2TJDFT.txt                    :
2                ADI2TJDFT.txt             Conselho
3                ADI2TJDFT.txt             Especial
4                ADI2TJDFT.txt               Classe
...                        ...                  ...
193487  ACORDAOTCU25052016.txt  Ministro-Substituto
193488  ACORDAOTCU25052016.txt              AUGUSTO
193489  ACORDAOTCU25052016.txt              SHERMAN
193490  ACORDAOTCU25052016.txt           CAVALCANTI
193491  ACORDAOTCU25052016.txt              Relator

[193492 rows x 2 columns]

In [ ]:
tabela_palavras.to_csv('palavras.csv', index=False, sep = '\t')

### Rotulação

O formato IOB (Inside-Outside-Beginning) é amplamente utilizado para rotular sequências de texto em tarefas de NLP, principalmente em tarefas de reconhecimento de entidades nomeadas (NER). Este formato ajuda a identificar palavras ou frases que pertencem a categorias específicas, como nomes de pessoas, organizações, locais e datas.

Esse formato é um esquema de rotulação que classifica as palavras de uma sequência de texto em três categorias:

- B- (Beginning): indica o início de uma entidade. É usado para marcar a primeira palavra de uma entidade nomeada.
- I- (Inside): indica que a palavra faz parte de uma entidade, mas não é a primeira palavra. Todas as palavras subsequentes que ainda pertencem à mesma entidade são marcadas com "I".
- O (Outside): indica que a palavra não faz parte de nenhuma entidade nomeada. É utilizada para palavras que não pertencem a nenhuma categoria específica de interesse.

**Vantagens do formato IOB**

Simplicidade: é fácil de entender e aplicar. Cada palavra recebe um rótulo que indica claramente se pertence a uma entidade e, em caso positivo, se é o início ou parte de uma entidade.
- Versatilidade: pode ser utilizado para diferentes tipos de entidades, bastando adaptar os rótulos (por exemplo, B-PESSOA, I-PESSOA, B-LOCAL, I-LOCAL, B-CARGO, I-CARGO).
- Facilidade de treinamento: é um formato muito utilizado em modelos de aprendizado de máquina para NLP, pois fornece informações ricas e estruturadas sobre as entidades no texto.

**Limitações do formato IOB**

Embora seja amplamente utilizado, o formato IOB tem algumas limitações:
- Confusão em casos ambíguos: em algumas situações, pode ser difícil decidir onde começa e termina uma entidade, especialmente em textos complexos.
- Depende de segmentação prévia: para utilizar o formato IOB, é necessário que o texto esteja devidamente tokenizado (dividido em palavras ou subpalavras).

**Alternativas ao formato IOB**

Existem variações do formato IOB, como o IOB2 e o BIOES:

- IOB2: semelhante ao IOB, mas todos os rótulos de entidade começam com "B-" independentemente de serem a primeira palavra de uma entidade.
- BIOES: adiciona dois rótulos adicionais: "E-" (End), que indica a última palavra de uma entidade, e "S-" (Single), que marca uma entidade que consiste em uma única palavra.

In [ ]:
tabela_palavras = pd.read_csv('/content/palavras_IOB.tsv', sep='\t')
tabela_palavras

                          arquivo     palavra          label
0                     TCU4687.txt       GRUPO              O
1                     TCU4687.txt           I              O
2                     TCU4687.txt      CLASSE              O
3                     TCU4687.txt          II              O
4                     TCU4687.txt          2ª  B-ORGANIZACAO
...                           ...         ...            ...
229272  RR2574407120025020372.txt          de              O
229273  RR2574407120025020372.txt      Chaves              O
229274  RR2574407120025020372.txt    Públicas              O
229275  RR2574407120025020372.txt  Brasileira              O
229276  RR2574407120025020372.txt           .              O

[229277 rows x 3 columns]

In [ ]:
tabela_palavras['label'].unique()

array(['O', 'B-ORGANIZACAO', 'I-ORGANIZACAO', 'B-JURISPRUDENCIA',
       'I-JURISPRUDENCIA', 'B-PESSOA', 'I-PESSOA', 'B-LEGISLACAO',
       'I-LEGISLACAO', 'B-TEMPO', 'B-LOCAL', 'I-LOCAL', 'I-TEMPO'],
      dtype=object)

In [ ]:
# converter para formato spacy

grupos_arquivos = tabela_palavras.groupby('arquivo')
grupos_arquivos.get_group('ADI2TJDFT.txt')

             arquivo   palavra          label
46105  ADI2TJDFT.txt     Órgão              O
46106  ADI2TJDFT.txt         :              O
46107  ADI2TJDFT.txt  Conselho  B-ORGANIZACAO
46108  ADI2TJDFT.txt  Especial  I-ORGANIZACAO
46109  ADI2TJDFT.txt    Classe              O
...              ...       ...            ...
55911  ADI2TJDFT.txt         a              O
55912  ADI2TJDFT.txt      ação              O
55913  ADI2TJDFT.txt         ,              O
55914  ADI2TJDFT.txt   maioria              O
55915  ADI2TJDFT.txt         .              O

[9811 rows x 3 columns]

In [ ]:
tabela_agrupada = grupos_arquivos.get_group('ADI2TJDFT.txt')[['palavra', 'label']].values
conteudo = ''
anotacoes = {'entities': []}
inicio_palavra = 0
fim_palavra = 0
for texto, label in tabela_agrupada:
    texto = str(texto)
    tamanho_texto = len(texto)+1

    inicio_palavra = fim_palavra
    fim_palavra = inicio_palavra + tamanho_texto

    if label != 'O':
        anotacao = (inicio_palavra, fim_palavra-1, label)
        anotacoes['entities'].append(anotacao)

    conteudo = conteudo + texto + ' '

In [ ]:
anotacoes

{'entities': [(8, 16, 'B-ORGANIZACAO'),
  (17, 25, 'I-ORGANIZACAO'),
  (91, 106, 'B-JURISPRUDENCIA'),
  (158, 166, 'B-LOCAL'),
  (167, 174, 'I-LOCAL'),
  (221, 227, 'B-ORGANIZACAO'),
  (228, 239, 'I-ORGANIZACAO'),
  (240, 242, 'I-ORGANIZACAO'),
  (243, 251, 'I-ORGANIZACAO'),
  (252, 259, 'I-ORGANIZACAO'),
  (298, 303, 'B-PESSOA'),
  (304, 311, 'I-PESSOA'),
  (358, 362, 'B-LEGISLACAO'),
  (363, 373, 'I-LEGISLACAO'),
  (374, 377, 'I-LEGISLACAO'),
  (378, 386, 'I-LEGISLACAO'),
  (389, 398, 'B-LEGISLACAO'),
  (401, 404, 'B-LEGISLACAO'),
  (405, 417, 'I-LEGISLACAO'),
  (418, 427, 'I-LEGISLACAO'),
  (428, 431, 'I-LEGISLACAO'),
  (432, 440, 'I-LEGISLACAO'),
  (474, 477, 'B-LEGISLACAO'),
  (478, 486, 'I-LEGISLACAO'),
  (487, 489, 'I-LEGISLACAO'),
  (490, 498, 'I-LEGISLACAO'),
  (499, 506, 'I-LEGISLACAO'),
  (575, 583, 'B-LOCAL'),
  (584, 591, 'I-LOCAL'),
  (653, 660, 'B-LEGISLACAO'),
  (661, 664, 'I-LEGISLACAO'),
  (665, 674, 'I-LEGISLACAO'),
  (686, 694, 'B-LEGISLACAO'),
  (695, 698, 'I-LEGISLACAO'),
  (699, 705, 'I-LEGISLACAO'),
  (711, 720, 'B-ORGANIZACAO'),
  (721, 731, 'I-ORGANIZACAO'),
  (732, 734, 'I-ORGANIZACAO'),
  (735, 745, 'I-ORGANIZACAO'),
  (746, 754, 'I-ORGANIZACAO'),
  (755, 759, 'B-ORGANIZACAO'),
  (767, 776, 'B-ORGANIZACAO'),
  (777, 779, 'I-ORGANIZACAO'),
  (780, 790, 'I-ORGANIZACAO'),
  (791, 800, 'I-ORGANIZACAO'),
  (801, 802, 'I-ORGANIZACAO'),
  (803, 812, 'I-ORGANIZACAO'),
  (813, 821, 'I-ORGANIZACAO'),
  (822, 827, 'B-ORGANIZACAO'),
  (856, 864, 'B-LOCAL'),
  (865, 872, 'I-LOCAL'),
  (1007, 1015, 'B-LOCAL'),
  (1016, 1023, 'I-LOCAL'),
  (1064, 1072, 'B-ORGANIZACAO'),
  (1073, 1081, 'I-ORGANIZACAO'),
  (1082, 1084, 'I-ORGANIZACAO'),
  (1085, 1093, 'I-ORGANIZACAO'),
  (1094, 1096, 'I-ORGANIZACAO'),
  (1097, 1104, 'I-ORGANIZACAO'),
  (1105, 1107, 'I-ORGANIZACAO'),
  (1108, 1116, 'I-ORGANIZACAO'),
  (1117, 1124, 'I-ORGANIZACAO'),
  (1143, 1148, 'B-PESSOA'),
  (1149, 1156, 'I-PESSOA'),
  (1167, 1171, 'B-PESSOA'),
  (1172, 1180, 'I-PESSOA'),
  (1189, 1194, 'B-PESSOA'),
  (1195, 1197, 'I-PESSOA'),
  (1198, 1206, 'I-PESSOA'),
  (1215, 1220, 'B-PESSOA'),
  (1221, 1227, 'I-PESSOA'),
  (1236, 1242, 'B-PESSOA'),
  (1243, 1254, 'I-PESSOA'),
  (1263, 1268, 'B-PESSOA'),
  (1269, 1275, 'I-PESSOA'),
  (1276, 1278, 'I-PESSOA'),
  (1279, 1282, 'I-PESSOA'),
  (1291, 1300, 'B-PESSOA'),
  (1301, 1307, 'I-PESSOA'),
  (1316, 1322, 'B-PESSOA'),
  (1323, 1330, 'I-PESSOA'),
  (1331, 1336, 'I-PESSOA'),
  (1337, 1343, 'I-PESSOA'),
  (1352, 1356, 'B-PESSOA'),
  (1357, 1362, 'I-PESSOA'),
  (1363, 1371, 'I-PESSOA'),
  (1380, 1388, 'B-PESSOA'),
  (1389, 1395, 'I-PESSOA'),
  (1396, 1401, 'I-PESSOA'),
  (1410, 1415, 'B-PESSOA'),
  (1416, 1422, 'I-PESSOA'),
  (1423, 1427, 'I-PESSOA'),
  (1436, 1439, 'B-PESSOA'),
  (1440, 1445, 'I-PESSOA'),
  (1446, 1452, 'I-PESSOA'),
  (1453, 1461, 'I-PESSOA'),
  (1462, 1467, 'I-PESSOA'),
  (1476, 1480, 'B-PESSOA'),
  (1481, 1487, 'I-PESSOA'),
  (1498, 1506, 'B-PESSOA'),
  (1507, 1515, 'I-PESSOA'),
  (1516, 1524, 'I-PESSOA'),
  (1533, 1541, 'B-PESSOA'),
  (1542, 1549, 'I-PESSOA'),
  (1550, 1553, 'I-PESSOA'),
  (1554, 1560, 'I-PESSOA'),
  (1569, 1575, 'B-PESSOA'),
  (1576, 1583, 'I-PESSOA'),
  (1627, 1633, 'B-PESSOA'),
  (1634, 1641, 'I-PESSOA'),
  (1779, 1787, 'B-LOCAL'),
  (1788, 1789, 'I-LOCAL'),
  (1790, 1792, 'I-LOCAL'),
  (1793, 1794, 'I-LOCAL'),
  (1797, 1799, 'B-TEMPO'),
  (1800, 1802, 'I-TEMPO'),
  (1803, 1807, 'I-TEMPO'),
  (1808, 1810, 'I-TEMPO'),
  (1811, 1815, 'I-TEMPO'),
  (1822, 1827, 'B-PESSOA'),
  (1828, 1835, 'I-PESSOA'),
  (1896, 1904, 'B-LOCAL'),
  (1905, 1912, 'I-LOCAL'),
  (1983, 1987, 'B-LEGISLACAO'),
  (1988, 1998, 'I-LEGISLACAO'),
  (1999, 2002, 'I-LEGISLACAO'),
  (2003, 2006, 'I-LEGISLACAO'),
  (2012, 2014, 'B-TEMPO'),
  (2015, 2017, 'I-TEMPO'),
  (2018, 2024, 'I-TEMPO'),
  (2025, 2027, 'I-TEMPO'),
  (2028, 2032, 'I-TEMPO'),
  (2037, 2042, 'B-LEGISLACAO'),
  (2048, 2050, 'B-TEMPO'),
  (2051, 2053, 'I-TEMPO'),
  (2054, 2059, 'I-TEMPO'),
  (2060, 2062, 'I-TEMPO'),
  (2063, 2067, 'I-TEMPO'),
  (2075, 2078, 'B-LEGISLACAO'),
  (2079, 2091, 'I-LEGISLACAO'),
  (2092, 2101, 'I-LEGISLACAO'),
  (2102, 2105, 'I-LEGISLACAO'),
  (2106, 2109, 'I-LEGISLACAO'),
  (2115, 2116, 'B-TEMPO'),
  (2117, 2119, 'I-TEMPO'),
  (2120, 2125, 'I-TEMPO'),
  (2126, 2128, 'I-TEMPO'),
  (2129, 2133, 'I-TEMPO'),
  (2180, 2186, 'B-LOCAL'),
  (2187, 2201, 'I-LOCAL'),
  (2202, 2204, 'I-LOCAL'),
  (2205, 2212, 'I-LOCAL'),
  (2213, 2215, 'B-LOCAL'),
  (2216, 2219, 'I-LOCAL'),
  (2252, 2259, 'B-LEGISLACAO'),
  (2260, 2262, 'I-LEGISLACAO'),
  (2263, 2264, 'I-LEGISLACAO'),
  (2265, 2269, 'I-LEGISLACAO'),
  (2270, 2272, 'I-LEGISLACAO'),
  (2273, 2274, 'I-LEGISLACAO'),
  (2275, 2277, 'I-LEGISLACAO'),
  (2278, 2279, 'I-LEGISLACAO'),
  (2280, 2283, 'I-LEGISLACAO'),
  (2284, 2285, 'I-LEGISLACAO'),
  (2286, 2291, 'I-LEGISLACAO'),
  (2292, 2294, 'I-LEGISLACAO'),
  (2295, 2296, 'I-LEGISLACAO'),
  (2297, 2300, 'I-LEGISLACAO'),
  (2301, 2302, 'I-LEGISLACAO'),
  (2303, 2304, 'I-LEGISLACAO'),
  (2305, 2308, 'I-LEGISLACAO'),
  (2309, 2310, 'I-LEGISLACAO'),
  (2311, 2316, 'I-LEGISLACAO'),
  (2317, 2319, 'I-LEGISLACAO'),
  (2320, 2323, 'I-LEGISLACAO'),
  (2324, 2332, 'I-LEGISLACAO'),
  (2333, 2335, 'I-LEGISLACAO'),
  (2336, 2344, 'I-LEGISLACAO'),
  (2345, 2352, 'I-LEGISLACAO'),
  (2353, 2357, 'B-LEGISLACAO'),
  (2774, 2778, 'B-LEGISLACAO'),
  (2779, 2789, 'I-LEGISLACAO'),
  (2790, 2793, 'I-LEGISLACAO'),
  (2794, 2802, 'I-LEGISLACAO'),
  (2805, 2815, 'B-LEGISLACAO'),
  (2830, 2833, 'B-LEGISLACAO'),
  (2834, 2846, 'I-LEGISLACAO'),
  (2847, 2856, 'I-LEGISLACAO'),
  (2857, 2860, 'I-LEGISLACAO'),
  (2861, 2869, 'I-LEGISLACAO'),
  (2940, 2946, 'B-ORGANIZACAO'),
  (2947, 2958, 'I-ORGANIZACAO'),
  (2959, 2961, 'I-ORGANIZACAO'),
  (2962, 2970, 'I-ORGANIZACAO'),
  (2971, 2978, 'I-ORGANIZACAO'),
  (3187, 3195, 'B-LOCAL'),
  (3196, 3203, 'I-LOCAL'),
  (3270, 3276, 'B-ORGANIZACAO'),
  (3277, 3286, 'I-ORGANIZACAO'),
  (3388, 3391, 'B-LEGISLACAO'),
  (3392, 3393, 'I-LEGISLACAO'),
  (3394, 3396, 'I-LEGISLACAO'),
  (3397, 3398, 'I-LEGISLACAO'),
  (3399, 3401, 'I-LEGISLACAO'),
  (3402, 3406, 'I-LEGISLACAO'),
  (3425, 3433, 'B-LOCAL'),
  (3434, 3441, 'I-LOCAL'),
  (3663, 3671, 'B-LOCAL'),
  (3672, 3679, 'I-LOCAL'),
  (4001, 4006, 'B-PESSOA'),
  (4007, 4014, 'I-PESSOA'),
  (4057, 4065, 'B-LOCAL'),
  (4066, 4073, 'I-LOCAL'),
  (4144, 4148, 'B-LEGISLACAO'),
  (4149, 4159, 'I-LEGISLACAO'),
  (4160, 4163, 'I-LEGISLACAO'),
  (4164, 4167, 'I-LEGISLACAO'),
  (4173, 4175, 'B-TEMPO'),
  (4176, 4178, 'I-TEMPO'),
  (4179, 4185, 'I-TEMPO'),
  (4186, 4188, 'I-TEMPO'),
  (4189, 4193, 'I-TEMPO'),
  (4198, 4203, 'B-LEGISLACAO'),
  (4209, 4211, 'B-TEMPO'),
  (4212, 4214, 'I-TEMPO'),
  (4215, 4220, 'I-TEMPO'),
  (4221, 4223, 'I-TEMPO'),
  (4224, 4228, 'I-TEMPO'),
  (4236, 4239, 'B-LEGISLACAO'),
  (4240, 4252, 'I-LEGISLACAO'),
  (4253, 4262, 'I-LEGISLACAO'),
  (4263, 4266, 'I-LEGISLACAO'),
  (4267, 4270, 'I-LEGISLACAO'),
  (4276, 4277, 'B-TEMPO'),
  (4278, 4280, 'I-TEMPO'),
  (4281, 4286, 'I-TEMPO'),
  (4287, 4289, 'I-TEMPO'),
  (4290, 4294, 'I-TEMPO'),
  (4341, 4347, 'B-LOCAL'),
  (4348, 4362, 'I-LOCAL'),
  (4363, 4365, 'I-LOCAL'),
  (4366, 4373, 'I-LOCAL'),
  (4374, 4376, 'B-LOCAL'),
  (4377, 4380, 'I-LOCAL'),
  (4663, 4670, 'B-LEGISLACAO'),
  (4671, 4673, 'I-LEGISLACAO'),
  (4674, 4675, 'I-LEGISLACAO'),
  (4676, 4680, 'I-LEGISLACAO'),
  (4681, 4683, 'I-LEGISLACAO'),
  (4684, 4685, 'I-LEGISLACAO'),
  (4686, 4688, 'I-LEGISLACAO'),
  (4689, 4690, 'I-LEGISLACAO'),
  (4691, 4694, 'I-LEGISLACAO'),
  (4695, 4696, 'I-LEGISLACAO'),
  (4697, 4702, 'I-LEGISLACAO'),
  (4703, 4705, 'I-LEGISLACAO'),
  (4706, 4707, 'I-LEGISLACAO'),
  (4708, 4711, 'I-LEGISLACAO'),
  (4712, 4713, 'I-LEGISLACAO'),
  (4714, 4715, 'I-LEGISLACAO'),
  (4716, 4719, 'I-LEGISLACAO'),
  (4720, 4721, 'I-LEGISLACAO'),
  (4722, 4727, 'I-LEGISLACAO'),
  (4728, 4730, 'I-LEGISLACAO'),
  (4731, 4734, 'I-LEGISLACAO'),
  (4735, 4743, 'I-LEGISLACAO'),
  (4744, 4746, 'I-LEGISLACAO'),
  (4747, 4755, 'I-LEGISLACAO'),
  (4756, 4763, 'I-LEGISLACAO'),
  (4764, 4768, 'B-LEGISLACAO'),
  (5001, 5004, 'B-LEGISLACAO'),
  (5005, 5013, 'I-LEGISLACAO'),
  (5014, 5016, 'I-LEGISLACAO'),
  (5017, 5025, 'I-LEGISLACAO'),
  (5026, 5033, 'I-LEGISLACAO'),
  (5104, 5109, 'B-LEGISLACAO'),
  (5110, 5115, 'I-LEGISLACAO'),
  (5260, 5266, 'B-LEGISLACAO'),
  (5267, 5268, 'I-LEGISLACAO'),
  (5269, 5270, 'I-LEGISLACAO'),
  (5271, 5272, 'I-LEGISLACAO'),
  (5273, 5275, 'I-LEGISLACAO'),
  (5276, 5280, 'I-LEGISLACAO'),
  (5281, 5282, 'I-LEGISLACAO'),
  (5283, 5285, 'I-LEGISLACAO'),
  (5286, 5289, 'I-LEGISLACAO'),
  (5290, 5291, 'I-LEGISLACAO'),
  (5292, 5295, 'I-LEGISLACAO'),
  (5296, 5298, 'I-LEGISLACAO'),
  (5299, 5304, 'I-LEGISLACAO'),
  (5305, 5310, 'I-LEGISLACAO'),
  (5416, 5419, 'B-LEGISLACAO'),
  (5420, 5421, 'I-LEGISLACAO'),
  (5422, 5425, 'I-LEGISLACAO'),
  (5426, 5427, 'I-LEGISLACAO'),
  (5428, 5429, 'I-LEGISLACAO'),
  (5430, 5432, 'I-LEGISLACAO'),
  (5433, 5435, 'I-LEGISLACAO'),
  (5436, 5448, 'I-LEGISLACAO'),
  (5449, 5456, 'I-LEGISLACAO'),
  (5568, 5580, 'B-LEGISLACAO'),
  (5944, 5952, 'B-ORGANIZACAO'),
  (5953, 5960, 'I-ORGANIZACAO'),
  (6180, 6188, 'B-ORGANIZACAO'),
  (6189, 6196, 'I-ORGANIZACAO'),
  (6222, 6231, 'B-ORGANIZACAO'),
  (6232, 6242, 'I-ORGANIZACAO'),
  (6295, 6300, 'B-PESSOA'),
  (6301, 6303, 'I-PESSOA'),
  (6304, 6309, 'I-PESSOA'),
  (6334, 6337, 'B-JURISPRUDENCIA'),
  (6338, 6340, 'I-JURISPRUDENCIA'),
  (6341, 6347, 'I-JURISPRUDENCIA'),
  (6363, 6366, 'B-LEGISLACAO'),
  (6367, 6375, 'I-LEGISLACAO'),
  (6376, 6378, 'I-LEGISLACAO'),
  (6379, 6387, 'I-LEGISLACAO'),
  (6388, 6395, 'I-LEGISLACAO'),
  (6628, 6637, 'B-ORGANIZACAO'),
  (6638, 6648, 'I-ORGANIZACAO'),
  (6772, 6780, 'B-LOCAL'),
  (6781, 6788, 'I-LOCAL'),
  (7011, 7013, 'B-TEMPO'),
  (7014, 7016, 'I-TEMPO'),
  (7017, 7021, 'I-TEMPO'),
  (7022, 7024, 'I-TEMPO'),
  (7025, 7029, 'I-TEMPO'),
  (7180, 7183, 'B-LEGISLACAO'),
  (7184, 7192, 'I-LEGISLACAO'),
  (7193, 7195, 'I-LEGISLACAO'),
  (7196, 7204, 'I-LEGISLACAO'),
  (7205, 7212, 'I-LEGISLACAO'),
  (7425, 7432, 'B-ORGANIZACAO'),
  (7433, 7441, 'I-ORGANIZACAO'),
  (7442, 7449, 'I-ORGANIZACAO'),
  (7455, 7458, 'B-JURISPRUDENCIA'),
  (7459, 7462, 'I-JURISPRUDENCIA'),
  (7463, 7472, 'I-JURISPRUDENCIA'),
  (7506, 7514, 'B-ORGANIZACAO'),
  (7515, 7517, 'I-ORGANIZACAO'),
  (7518, 7525, 'I-ORGANIZACAO'),
  (7526, 7528, 'I-ORGANIZACAO'),
  (7529, 7537, 'I-ORGANIZACAO'),
  (7538, 7545, 'I-ORGANIZACAO'),
  (7546, 7547, 'I-ORGANIZACAO'),
  (7548, 7551, 'I-ORGANIZACAO'),
  (7552, 7563, 'I-ORGANIZACAO'),
  (7648, 7651, 'B-LEGISLACAO'),
  (7652, 7660, 'I-LEGISLACAO'),
  (7661, 7663, 'I-LEGISLACAO'),
  (7664, 7672, 'I-LEGISLACAO'),
  (7673, 7680, 'I-LEGISLACAO'),
  (7845, 7853, 'B-ORGANIZACAO'),
  (7854, 7856, 'I-ORGANIZACAO'),
  (7857, 7864, 'I-ORGANIZACAO'),
  (7865, 7867, 'I-ORGANIZACAO'),
  (7868, 7876, 'I-ORGANIZACAO'),
  (7877, 7884, 'I-ORGANIZACAO'),
  (7885, 7886, 'I-ORGANIZACAO'),
  (7887, 7890, 'I-ORGANIZACAO'),
  (7891, 7902, 'I-ORGANIZACAO'),
  (7941, 7946, 'B-LEGISLACAO'),
  (7947, 7952, 'I-LEGISLACAO'),
  (8139, 8147, 'B-LOCAL'),
  (8148, 8155, 'I-LOCAL'),
  (8363, 8371, 'B-LOCAL'),
  (8372, 8379, 'I-LOCAL'),
  (8544, 8547, 'B-LEGISLACAO'),
  (8548, 8550, 'I-LEGISLACAO'),
  (8551, 8554, 'I-LEGISLACAO'),
  (8560, 8562, 'B-TEMPO'),
  (8563, 8565, 'I-TEMPO'),
  (8566, 8572, 'I-TEMPO'),
  (8573, 8575, 'I-TEMPO'),
  (8576, 8580, 'I-TEMPO'),
  (8611, 8619, 'B-PESSOA'),
  (8620, 8629, 'I-PESSOA'),
  (8674, 8682, 'B-LOCAL'),
  (8683, 8690, 'I-LOCAL'),
  (8751, 8755, 'B-LOCAL'),
  (8756, 8758, 'I-LOCAL'),
  (8759, 8767, 'I-LOCAL'),
  (8768, 8774, 'I-LOCAL'),
  (8775, 8777, 'I-LOCAL'),
  (8778, 8785, 'I-LOCAL'),
  (8813, 8819, 'B-ORGANIZACAO'),
  (8820, 8831, 'I-ORGANIZACAO'),
  (8832, 8834, 'I-ORGANIZACAO'),
  (8835, 8843, 'I-ORGANIZACAO'),
  (8844, 8851, 'I-ORGANIZACAO'),
  (8888, 8889, 'B-LEGISLACAO'),
  (8890, 8892, 'I-LEGISLACAO'),
  (8893, 8895, 'I-LEGISLACAO'),
  (8896, 8899, 'I-LEGISLACAO'),
  (8900, 8901, 'I-LEGISLACAO'),
  (8902, 8904, 'I-LEGISLACAO'),
  (8905, 8907, 'I-LEGISLACAO'),
  (8908, 8911, 'I-LEGISLACAO'),
  (8912, 8920, 'I-LEGISLACAO'),
  (8921, 8923, 'I-LEGISLACAO'),
  (8924, 8932, 'I-LEGISLACAO'),
  (8933, 8940, 'I-LEGISLACAO'),
  (8945, 8948, 'B-LEGISLACAO'),
  (8949, 8951, 'I-LEGISLACAO'),
  (8952, 8955, 'I-LEGISLACAO'),
  (8961, 8963, 'B-TEMPO'),
  (8964, 8966, 'I-TEMPO'),
  (8967, 8973, 'I-TEMPO'),
  (8974, 8976, 'I-TEMPO'),
  (8977, 8981, 'I-TEMPO'),
  (9038, 9042, 'B-LOCAL'),
  (9043, 9045, 'I-LOCAL'),
  (9046, 9054, 'I-LOCAL'),
  (9055, 9061, 'I-LOCAL'),
  (9062, 9063, 'I-LOCAL'),
  (9064, 9066, 'I-LOCAL'),
  (9067, 9074, 'I-LOCAL'),
  (9099, 9102, 'B-LEGISLACAO'),
  (9103, 9105, 'I-LEGISLACAO'),
  (9106, 9109, 'I-LEGISLACAO'),
  (9115, 9117, 'B-TEMPO'),
  (9118, 9120, 'I-TEMPO'),
  (9121, 9129, 'I-TEMPO'),
  (9130, 9132, 'I-TEMPO'),
  (9133, 9137, 'I-TEMPO'),
  (9193, 9197, 'B-LOCAL'),
  (9198, 9205, 'I-LOCAL'),
  (9427, 9434, 'B-LEGISLACAO'),
  (9435, 9437, 'I-LEGISLACAO'),
  (9438, 9444, 'I-LEGISLACAO'),
  (9450, 9452, 'B-TEMPO'),
  (9453, 9455, 'I-TEMPO'),
  (9456, 9462, 'I-TEMPO'),
  (9463, 9465, 'I-TEMPO'),
  (9466, 9470, 'I-TEMPO'),
  (9482, 9492, 'B-ORGANIZACAO'),
  (9493, 9495, 'I-ORGANIZACAO'),
  (9496, 9505, 'I-ORGANIZACAO'),
  (9506, 9508, 'I-ORGANIZACAO'),
  (9509, 9516, 'I-ORGANIZACAO'),
  (9542, 9546, 'B-LOCAL'),
  (9547, 9549, 'I-LOCAL'),
  (9550, 9558, 'I-LOCAL'),
  (9559, 9565, 'I-LOCAL'),
  (9566, 9567, 'I-LOCAL'),
  (9568, 9570, 'I-LOCAL'),
  (9571, 9578, 'I-LOCAL'),
  (9622, 9626, 'B-LOCAL'),
  (9627, 9629, 'I-LOCAL'),
  (9630, 9638, 'I-LOCAL'),
  (9639, 9648, 'I-LOCAL'),
  (9649, 9651, 'I-LOCAL'),
  (9652, 9656, 'I-LOCAL'),
  (9657, 9664, 'I-LOCAL'),
  (9922, 9925, 'B-LEGISLACAO'),
  (9926, 9928, 'I-LEGISLACAO'),
  (9929, 9934, 'I-LEGISLACAO'),
  (9940, 9942, 'B-TEMPO'),
  (9943, 9945, 'I-TEMPO'),
  (9946, 9951, 'I-TEMPO'),
  (9952, 9954, 'I-TEMPO'),
  (9955, 9959, 'I-TEMPO'),
  (9992, 9996, 'B-PESSOA'),
  (9997, 10002, 'I-PESSOA'),
  (10089, 10095, 'B-LOCAL'),
  (10096, 10110, 'I-LOCAL'),
  (10111, 10113, 'I-LOCAL'),
  (10114, 10121, 'I-LOCAL'),
  (10122, 10124, 'B-LOCAL'),
  (10125, 10128, 'I-LOCAL'),
  (10148, 10154, 'B-ORGANIZACAO'),
  (10155, 10166, 'I-ORGANIZACAO'),
  (10167, 10169, 'I-ORGANIZACAO'),
  (10170, 10178, 'I-ORGANIZACAO'),
  (10179, 10186, 'I-ORGANIZACAO'),
  (10213, 10221, 'B-LOCAL'),
  (10222, 10229, 'I-LOCAL'),
  (10246, 10247, 'B-LEGISLACAO'),
  (10248, 10250, 'I-LEGISLACAO'),
  (10251, 10253, 'I-LEGISLACAO'),
  (10254, 10257, 'I-LEGISLACAO'),
  (10258, 10259, 'I-LEGISLACAO'),
  (10260, 10262, 'I-LEGISLACAO'),
  (10263, 10265, 'I-LEGISLACAO'),
  (10266, 10269, 'I-LEGISLACAO'),
  (10270, 10278, 'I-LEGISLACAO'),
  (10279, 10281, 'I-LEGISLACAO'),
  (10282, 10290, 'I-LEGISLACAO'),
  (10291, 10298, 'I-LEGISLACAO'),
  (10334, 10340, 'B-ORGANIZACAO'),
  (10341, 10352, 'I-ORGANIZACAO'),
  (10353, 10355, 'I-ORGANIZACAO'),
  (10356, 10364, 'I-ORGANIZACAO'),
  (10365, 10372, 'I-ORGANIZACAO'),
  (10536, 10542, 'B-LOCAL'),
  (10543, 10557, 'I-LOCAL'),
  (10558, 10560, 'I-LOCAL'),
  (10561, 10568, 'I-LOCAL'),
  (10569, 10571, 'B-LOCAL'),
  (10572, 10575, 'I-LOCAL'),
  (10612, 10619, 'B-LOCAL'),
  (10620, 10621, 'I-LOCAL'),
  (10622, 10623, 'I-LOCAL'),
  (10624, 10625, 'I-LOCAL'),
  (10644, 10651, 'B-LOCAL'),
  (10652, 10654, 'I-LOCAL'),
  (10655, 10658, 'I-LOCAL'),
  (10692, 10699, 'B-LOCAL'),
  (10700, 10702, 'I-LOCAL'),
  (10703, 10706, 'I-LOCAL'),
  (10736, 10742, 'B-LOCAL'),
  (10743, 10757, 'I-LOCAL'),
  (10758, 10760, 'I-LOCAL'),
  (10761, 10768, 'I-LOCAL'),
  (11360, 11363, 'B-LEGISLACAO'),
  (11364, 11376, 'I-LEGISLACAO'),
  (11377, 11379, 'I-LEGISLACAO'),
  (11380, 11383, 'I-LEGISLACAO'),
  (11389, 11390, 'B-TEMPO'),
  (11391, 11393, 'I-TEMPO'),
  (11394, 11399, 'I-TEMPO'),
  (11400, 11402, 'I-TEMPO'),
  (11403, 11407, 'I-TEMPO'),
  (11440, 11445, 'B-PESSOA'),
  (11446, 11453, 'I-PESSOA'),
  (11516, 11522, 'B-LOCAL'),
  (11523, 11537, 'I-LOCAL'),
  (11538, 11540, 'I-LOCAL'),
  (11541, 11548, 'I-LOCAL'),
  (11549, 11551, 'B-LOCAL'),
  (11552, 11555, 'I-LOCAL'),
  (11574, 11580, 'B-ORGANIZACAO'),
  (11581, 11592, 'I-ORGANIZACAO'),
  (11593, 11595, 'I-ORGANIZACAO'),
  (11596, 11604, 'I-ORGANIZACAO'),
  (11605, 11612, 'I-ORGANIZACAO'),
  (11638, 11639, 'B-LEGISLACAO'),
  (11640, 11642, 'I-LEGISLACAO'),
  (11643, 11645, 'I-LEGISLACAO'),
  (11646, 11649, 'I-LEGISLACAO'),
  (11650, 11651, 'I-LEGISLACAO'),
  (11652, 11654, 'I-LEGISLACAO'),
  (11655, 11657, 'I-LEGISLACAO'),
  (11658, 11661, 'I-LEGISLACAO'),
  (11662, 11670, 'I-LEGISLACAO'),
  (11671, 11673, 'I-LEGISLACAO'),
  (11674, 11682, 'I-LEGISLACAO'),
  (11683, 11690, 'I-LEGISLACAO'),
  (11768, 11776, 'B-LOCAL'),
  (11777, 11784, 'I-LOCAL'),
  (11800, 11806, 'B-ORGANIZACAO'),
  (11807, 11818, 'I-ORGANIZACAO'),
  (11819, 11821, 'I-ORGANIZACAO'),
  (11822, 11830, 'I-ORGANIZACAO'),
  (11831, 11838, 'I-ORGANIZACAO'),
  (12023, 12029, 'B-LOCAL'),
  (12030, 12044, 'I-LOCAL'),
  (12045, 12047, 'I-LOCAL'),
  (12048, 12055, 'I-LOCAL'),
  (12056, 12058, 'B-LOCAL'),
  (12059, 12062, 'I-LOCAL'),
  (12131, 12137, 'B-LOCAL'),
  (12138, 12145, 'I-LOCAL'),
  (12146, 12152, 'I-LOCAL'),
  (12153, 12161, 'I-LOCAL'),
  (12162, 12166, 'I-LOCAL'),
  (12182, 12188, 'B-LOCAL'),
  (12189, 12203, 'I-LOCAL'),
  (12204, 12206, 'I-LOCAL'),
  (12207, 12214, 'I-LOCAL'),
  (12215, 12217, 'B-LOCAL'),
  (12218, 12221, 'I-LOCAL'),
  (12333, 12340, 'B-LOCAL'),
  (12341, 12347, 'I-LOCAL'),
  (12348, 12352, 'I-LOCAL'),
  (13186, 13191, 'B-LEGISLACAO'),
  (13192, 13194, 'I-LEGISLACAO'),
  (13195, 13197, 'I-LEGISLACAO'),
  (13198, 13201, 'I-LEGISLACAO'),
  (13202, 13214, 'I-LEGISLACAO'),
  (13215, 13217, 'I-LEGISLACAO'),
  (13218, 13220, 'I-LEGISLACAO'),
  (13226, 13228, 'B-TEMPO'),
  (13229, 13231, 'I-TEMPO'),
  (13232, 13237, 'I-TEMPO'),
  (13238, 13240, 'I-TEMPO'),
  (13241, 13245, 'I-TEMPO'),
  (13488, 13494, 'B-LOCAL'),
  (13495, 13509, 'I-LOCAL'),
  (13510, 13512, 'I-LOCAL'),
  (13513, 13520, 'I-LOCAL'),
  (13521, 13523, 'B-LOCAL'),
  (13524, 13527, 'I-LOCAL'),
  (13810, 13813, 'B-LEGISLACAO'),
  (13814, 13822, 'I-LEGISLACAO'),
  (13823, 13825, 'I-LEGISLACAO'),
  (13826, 13834, 'I-LEGISLACAO'),
  (13835, 13842, 'I-LEGISLACAO'),
  (13905, 13913, 'B-ORGANIZACAO'),
  (13914, 13921, 'I-ORGANIZACAO'),
  (13972, 13980, 'B-LOCAL'),
  (14097, 14104, 'B-LEGISLACAO'),
  (14105, 14108, 'I-LEGISLACAO'),
  (14109, 14115, 'I-LEGISLACAO'),
  (14121, 14122, 'B-TEMPO'),
  (14123, 14125, 'I-TEMPO'),
  (14126, 14133, 'I-TEMPO'),
  (14134, 14136, 'I-TEMPO'),
  (14137, 14141, 'I-TEMPO'),
  (14149, 14157, 'B-LEGISLACAO'),
  (14158, 14161, 'I-LEGISLACAO'),
  (14162, 14165, 'I-LEGISLACAO'),
  (14171, 14172, 'B-TEMPO'),
  (14173, 14175, 'I-TEMPO'),
  (14176, 14183, 'I-TEMPO'),
  (14184, 14186, 'I-TEMPO'),
  (14187, 14191, 'I-TEMPO'),
  (14203, 14212, 'B-ORGANIZACAO'),
  (14213, 14223, 'I-ORGANIZACAO'),
  (14224, 14226, 'I-ORGANIZACAO'),
  (14227, 14237, 'I-ORGANIZACAO'),
  (14238, 14246, 'I-ORGANIZACAO'),
  (14249, 14253, 'B-ORGANIZACAO'),
  (14261, 14270, 'B-ORGANIZACAO'),
  (14271, 14273, 'I-ORGANIZACAO'),
  (14274, 14284, 'I-ORGANIZACAO'),
  (14285, 14294, 'I-ORGANIZACAO'),
  (14295, 14296, 'I-ORGANIZACAO'),
  (14297, 14306, 'I-ORGANIZACAO'),
  (14307, 14315, 'I-ORGANIZACAO'),
  (14318, 14323, 'B-ORGANIZACAO'),
  (14349, 14355, 'B-LEGISLACAO'),
  (14356, 14357, 'I-LEGISLACAO'),
  (14358, 14361, 'I-LEGISLACAO'),
  (14362, 14370, 'I-LEGISLACAO'),
  (14371, 14374, 'I-LEGISLACAO'),
  (14375, 14377, 'I-LEGISLACAO'),
  (14383, 14385, 'B-TEMPO'),
  (14386, 14388, 'I-TEMPO'),
  (14389, 14397, 'I-TEMPO'),
  (14398, 14400, 'I-TEMPO'),
  (14401, 14405, 'I-TEMPO'),
  (14416, 14424, 'B-TEMPO'),
  (14490, 14498, 'B-ORGANIZACAO'),
  (14499, 14506, 'I-ORGANIZACAO'),
  (14522, 14528, 'B-ORGANIZACAO'),
  (14529, 14540, 'I-ORGANIZACAO'),
  (14659, 14667, 'B-LOCAL'),
  (14668, 14675, 'I-LOCAL'),
  (15014, 15022, 'B-ORGANIZACAO'),
  (15023, 15030, 'I-ORGANIZACAO'),
  (15492, 15500, 'B-ORGANIZACAO'),
  (15501, 15508, 'I-ORGANIZACAO'),
  (15826, 15834, 'B-LOCAL'),
  (15835, 15842, 'I-LOCAL'),

In [ ]:
conteudo.find('Conselho Especial')

8

In [ ]:
conteudo.find('Conselho Especial') + len('Conselho Especial')

25

### Transformando todos os dados para formato correto

In [ ]:
arquivos = grupos_arquivos.groups.keys()
arquivos

dict_keys(['AC1TCU.txt', 'AC1TJAC.txt', 'AC1TJMG.txt', 'AC2.txt', 'ACORDAOTCU25052016.txt', 'ADI2TJDFT.txt', 'AIAgRAgI6193ARAGUARIMG.txt', 'AIRR15708820115050222.txt', 'AIRR3999520145020086.txt', 'AP00000794920137060006.txt', 'AP00001415620157010201.txt', 'AP00001441420167030203.txt', 'AP771420167080008PA.txt', 'Ag10000170733596001.txt', 'Ag10105170208398001.txt', 'AgAIRR11889820145030011.txt', 'AgCr10582160008758001.txt', 'AgRgSTJ1.txt', 'AgRgSTJ2.txt', 'AgRgTSE1.txt', 'AgRgTSE3.txt', 'CP32320177080008PA.txt', 'DespSEPLAGDF.txt', 'ED1STM.txt', 'ED1TJAC.txt', 'EDAgRgTSE2.txt', 'EDEDARR208420135040232.txt', 'EDRR1TST.txt', 'EEDRR9715120105020002.txt', 'ERR731004520105130003.txt', 'HC110260SP.txt', 'HC151914AgRES.txt', 'HC340624SP.txt', 'HC418951PR.txt', 'HC70000845920187000000.txt', 'Lei11788.txt', 'LoaDF2018.txt', 'Pet128TSE5.txt', 'Port77DF.txt', 'REE5908TSE4.txt', 'REsp1583083RS.txt', 'RR2574407120025020372.txt', 'RR474820145230056.txt', 'RR942006420095040028.txt', 'Rcl3495STJ.txt', 'TCU4687.txt', 'TSTRR16037920105200001.txt', 'adi3767.txt', 'airr801422012.txt', 'lei11340.txt'])

In [ ]:
documentos = []
for arquivo in arquivos:
    documento = []
    tabela_agrupada = grupos_arquivos.get_group(arquivo)[['palavra', 'label']].values
    conteudo = ''
    anotacoes = {'entities': []}
    inicio_palavra = 0
    fim_palavra = 0
    for texto, label in tabela_agrupada:
        texto = str(texto)
        tamanho_texto = len(texto)+1

        inicio_palavra = fim_palavra
        fim_palavra = inicio_palavra + tamanho_texto

        if label != 'O':
            anotacao = (inicio_palavra, fim_palavra-1, label)
            anotacoes['entities'].append(anotacao)

        conteudo = conteudo + texto + ' '

    documento = (conteudo, anotacoes)
    documentos.append(documento)

In [ ]:
documentos

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
random.shuffle(documentos)

In [ ]:
print(type(documentos[2]))

<class 'tuple'>

In [ ]:
dados_train = documentos[:40]
dados_validacao = documentos[40:]

In [ ]:
dados_train

('Brastra.gif ( 4376 bytes ) Presidência da República Casa Civil Subchefia para Assuntos Jurídicos LEI Nº 11.340 , DE 7 DE AGOSTO DE 2006 . Vigência ( Vide ADI nº 4427 ) Cria mecanismos para coibir a violência doméstica e familiar contra a mulher , nos termos do § 8o do art . 226 da Constituição Federal , da Convenção sobre a Eliminação de Todas as Formas de Discriminação contra as Mulheres e da Convenção Interamericana para Prevenir , Punir e Erradicar a Violência contra a Mulher ; dispõe sobre a criação dos Juizados de Violência Doméstica e Familiar contra a Mulher ; altera o Código de Processo Penal , o Código Penal e a Lei de Execução Penal ; e dá outras providências . O PRESIDENTE DA REPÚBLICA Faço saber que o Congresso Nacional decreta e eu sanciono a seguinte Lei : TÍTULO I DISPOSIÇÕES PRELIMINARES Art . 1o Esta Lei cria mecanismos para coibir e prevenir a violência doméstica e familiar contra a mulher , nos termos do § 8o do art . 226 da Constituição Federal , da Convenção sobre a Eliminação de Todas as Formas de Violência contra a Mulher , da Convenção Interamericana para Prevenir , Punir e Erradicar a Violência contra a Mulher e de outros tratados internacionais ratificados pela República Federativa do Brasil ; dispõe sobre a criação dos Juizados de Violência Doméstica e Familiar contra a Mulher ; e estabelece medidas de assistência e proteção às mulheres em situação de violência doméstica e familiar . Art . 2o Toda mulher , independentemente de classe , raça , etnia , orientação sexual , renda , cultura , nível educacional , idade e religião , goza dos direitos fundamentais inerentes à pessoa humana , sendo-lhe asseguradas as oportunidades e facilidades para viver sem violência , preservar sua saúde física e mental e seu aperfeiçoamento moral , intelectual e social . Art . 3o Serão asseguradas às mulheres as condições para o exercício efetivo dos direitos à vida , à segurança , à saúde , à alimentação , à educação , à cultura , à moradia , ao acesso à justiça , ao esporte , ao lazer , ao trabalho , à cidadania , à liberdade , à dignidade , ao respeito e à convivência familiar e comunitária . § 1o O poder público desenvolverá políticas que visem garantir os direitos humanos das mulheres no âmbito das relações domésticas e familiares no sentido de resguardá-las de toda forma de negligência , discriminação , exploração , violência , crueldade e opressão . § 2o Cabe à família , à sociedade e ao poder público criar as condições necessárias para o efetivo exercício dos direitos enunciados no caput . Art . 4o Na interpretação desta Lei , serão considerados os fins sociais a que ela se destina e , especialmente , as condições peculiares das mulheres em situação de violência doméstica e familiar . TÍTULO II DA VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER CAPÍTULO I DISPOSIÇÕES GERAIS Art . 5o Para os efeitos desta Lei , configura violência doméstica e familiar contra a mulher qualquer ação ou omissão baseada no gênero que lhe cause morte , lesão , sofrimento físico , sexual ou psicológico e dano moral ou patrimonial : ( Vide Lei complementar nº 150 , de 2015 ) I - no âmbito da unidade doméstica , compreendida como o espaço de convívio permanente de pessoas , com ou sem vínculo familiar , inclusive as esporadicamente agregadas ; II - no âmbito da família , compreendida como a comunidade formada por indivíduos que são ou se consideram aparentados , unidos por laços naturais , por afinidade ou por vontade expressa ; III - em qualquer relação íntima de afeto , na qual o agressor conviva ou tenha convivido com a ofendida , independentemente de coabitação . Parágrafo único . As relações pessoais enunciadas neste artigo independem de orientação sexual . Art . 6o A violência doméstica e familiar contra a mulher constitui uma das formas de violação dos direitos humanos . CAPÍTULO II DAS FORMAS DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CONTRA A MULHER Art . 7o São formas de violência doméstica e familiar contra a mulher , entre outras : I - a violência física , entendida como qualquer conduta que ofenda sua integridade ou saúde corporal ; II - a violência psicológica , entendida como qualquer conduta que lhe cause dano emocional e diminuição da auto-estima ou que lhe prejudique e perturbe o pleno desenvolvimento ou que vise degradar ou controlar suas ações , comportamentos , crenças e decisões , mediante ameaça , constrangimento , humilhação , manipulação , isolamento , vigilância constante , perseguição contumaz , insulto , chantagem , ridicularização , exploração e limitação do direito de ir e vir ou qualquer outro meio que lhe cause prejuízo à saúde psicológica e à autodeterminação ; III - a violência sexual , entendida como qualquer conduta que a constranja a presenciar , a manter ou a participar de relação sexual não desejada , mediante intimidação , ameaça , coação ou uso da força ; que a induza a comercializar ou a utilizar , de qualquer modo , a sua sexualidade , que a impeça de usar qualquer método contraceptivo ou que a force ao matrimônio , à gravidez , ao aborto ou à prostituição , mediante coação , chantagem , suborno ou manipulação ; ou que limite ou anule o exercício de seus direitos sexuais e reprodutivos ; IV - a violência patrimonial , entendida como qualquer conduta que configure retenção , subtração , destruição parcial ou total de seus objetos , instrumentos de trabalho , documentos pessoais , bens , valores e direitos ou recursos econômicos , incluindo os destinados a satisfazer suas necessidades ; V - a violência moral , entendida como qualquer conduta que configure calúnia , difamação ou injúria . TÍTULO III DA ASSISTÊNCIA À MULHER EM SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR CAPÍTULO I DAS MEDIDAS INTEGRADAS DE PREVENÇÃO Art . 8o A política pública que visa coibir a violência doméstica e familiar contra a mulher far-se-á por meio de um conjunto articulado de ações da União , dos Estados , do Distrito Federal e dos Municípios e de ações não-governamentais , tendo por diretrizes : I - a integração operacional do Poder Judiciário , do Ministério Público e da Defensoria Pública com as áreas de segurança pública , assistência social , saúde , educação , trabalho e habitação ; II - a promoção de estudos e pesquisas , estatísticas e outras informações relevantes , com a perspectiva de gênero e de raça ou etnia , concernentes às causas , às conseqüências e à freqüência da violência doméstica e familiar contra a mulher , para a sistematização de dados , a serem unificados nacionalmente , e a avaliação periódica dos resultados das medidas adotadas ; III - o respeito , nos meios de comunicação social , dos valores éticos e sociais da pessoa e da família , de forma a coibir os papéis estereotipados que legitimem ou exacerbem a violência doméstica e familiar , de acordo com o estabelecido no inciso III do art . 1o , no inciso IV do art . 3o e no inciso IV do art . 221 da Constituição Federal ; IV - a implementação de atendimento policial especializado para as mulheres , em particular nas Delegacias de Atendimento à Mulher ; V - a promoção e a realização de campanhas educativas de prevenção da violência doméstica e familiar contra a mulher , voltadas ao público escolar e à sociedade em geral , e a difusão desta Lei e dos instrumentos de proteção aos direitos humanos das mulheres ; VI - a celebração de convênios , protocolos , ajustes , termos ou outros instrumentos de promoção de parceria entre órgãos governamentais ou entre estes e entidades não-governamentais , tendo por objetivo a implementação de programas de erradicação da violência doméstica e familiar contra a mulher ; VII - a capacitação permanente das Polícias Civil e Militar , da Guarda Municipal , do Corpo de Bombeiros e dos profissionais pertencentes aos órgãos e às áreas enunciados no inciso I quanto às questões de gênero e de raça ou etnia ; VIII - a promoção de programas educacionais que disseminem valores éticos de irrestrito respeito à dignidade da pessoa humana com a perspectiva de gênero e de raça ou etnia ; IX - o destaque , nos currículos escolares de todos os níveis de ensino , para os conteúdos relativos aos direitos humanos , à eqüidade de gênero e de raça ou etnia e ao problema da violência doméstica e familiar contra a mulher . CAPÍTULO II DA ASSISTÊNCIA À MULHER EM SITUAÇÃO DE VIOLÊNCIA DOMÉSTICA E FAMILIAR Art . 9o A assistência à mulher em situação de violência doméstica e familiar será prestada de forma articulada e conforme os princípios e as diretrizes previstos na Lei Orgânica da Assistência Social , no Sistema Único de Saúde , no Sistema Único de Segurança Pública , entre outras normas e políticas públicas de proteção , e emergencialmente quando for o caso . § 1o O juiz determinará , por prazo certo , a inclusão da mulher em situação de violência doméstica e familiar no cadastro de programas assistenciais do governo federal , estadual e municipal . § 2o O juiz assegurará à mulher em situação de violência doméstica e familiar , para preservar sua integridade física e psicológica : I - acesso prioritário à remoção quando servidora pública , integrante da administração direta ou indireta ; II - manutenção do vínculo trabalhista , quando necessário o afastamento do local de trabalho , por até seis meses . § 3o A assistência à mulher em situação de violência doméstica e familiar compreenderá o acesso aos benefícios decorrentes do desenvolvimento científico e tecnológico , incluindo os serviços de contracepção de emergência , a profilaxia das Doenças Sexualmente Transmissíveis ( DST ) e da Síndrome da Imunodeficiência Adquirida ( AIDS ) e outros procedimentos médicos necessários e cabíveis nos casos de violência sexual . CAPÍTULO III DO ATENDIMENTO PELA AUTORIDADE POLICIAL Art . 10 . Na hipótese da iminência ou da prática de violência doméstica e familiar contra a mulher , a autoridade policial que tomar conhecimento da ocorrência adotará , de imediato , as providências legais cabíveis . Parágrafo único . Aplica-se o disposto no caput deste artigo ao descumprimento de medida protetiva de urgência deferida . Art . 10-A . É direito da mulher em situação de violência doméstica e familiar o atendimento policial e pericial especializado , ininterrupto e prestado por servidores - preferencialmente do sexo feminino - previamente capacitados . ( Incluíd pela Lei nº 13.505 , de 2017 ) § 1o A inquirição de mulher em situação de violência doméstica e familiar ou de testemunha de violência doméstica , quando se tratar de crime contra a mulher , obedecerá às seguintes diretrizes : ( Incluído pela Lei nº 13.505 , de 2017 ) I - salvaguarda da integridade física , psíquica e emocional da depoente , considerada a sua condição peculiar de pessoa em situação de violência doméstica e familiar ; ( Incluído pela Lei nº 13.505 , de 2017 ) II - garantia de que , em nenhuma hipótese , a mulher em situação de violência doméstica e familiar , familiares e testemunhas terão contato direto com investigados ou suspeitos e pessoas a eles relacionadas ; ( Incluído pela Lei nº 13.505 , de 2017 ) III - não revitimização da depoente , evitando sucessivas inquirições sobre o mesmo fato nos âmbitos criminal , cível e administrativo , bem como questionamentos sobre a vida privada . ( Incluído pela Lei nº 13.505 , de 2017 ) § 2o Na inquirição de mulher em situação de violência doméstica e familiar ou de testemunha de delitos de que trata esta Lei , adotar-se-á , preferencialmente , o seguinte procedimento : ( Incluído pela Lei nº 13.505 , de 2017 ) I - a inquirição será feita em recinto especialmente projetado para esse fim , o qual conterá os equipamentos próprios e adequados à idade da mulher em situação de violência doméstica e familiar ou testemunha e ao tipo e à gravidade da violência sofrida ; ( Incluído pela Lei nº 13.505 , de 2017 ) II - quando for o caso , a inquirição será intermediada por profissional especializado em violência doméstica e familiar designado pela autoridade judiciária ou policial ; ( Incluído pela Lei nº 13.505 , de 2017 ) III - o depoimento será registrado em meio eletrônico ou magnético , devendo a degravação e a mídia integrar o inquérito . ( Incluído pela Lei nº 13.505 , de 2017 ) Art . 11 . No atendimento à mulher em situação de violência doméstica e familiar , a autoridade policial deverá , entre outras providências : I - garantir proteção policial , quando necessário , comunicando de imediato ao Ministério Público e ao Poder Judiciário ; II - encaminhar a ofendida ao hospital ou posto de saúde e ao Instituto Médico Legal ; III - fornecer transporte para a ofendida e seus dependentes para abrigo ou local seguro , quando houver risco de vida ; IV - se necessário , acompanhar a ofendida para assegurar a retirada de seus pertences do local da ocorrência ou do domicílio familiar ; V - informar à ofendida os direitos a ela conferidos nesta Lei e os serviços disponíveis . Art . 12 . Em todos os casos de violência doméstica e familiar contra a mulher , feito o registro da ocorrência , deverá a autoridade policial adotar , de imediato , os seguintes procedimentos , sem prejuízo daqueles previstos no Código de Processo Penal : I - ouvir a ofendida , lavrar o boletim de ocorrência e tomar a representação a termo , se apresentada ; II - colher todas as provas que servirem para o esclarecimento do fato e de suas circunstâncias ; III - remeter , no prazo de 48 ( quarenta e oito ) horas , expediente apartado ao juiz com o pedido da ofendida , para a concessão de medidas protetivas de urgência ; IV - determinar que se proceda ao exame de corpo de delito da ofendida e requisitar outros exames periciais necessários ; V - ouvir o agressor e as testemunhas ; VI - ordenar a identificação do agressor e fazer juntar aos autos sua folha de antecedentes criminais , indicando a existência de mandado de prisão ou registro de outras ocorrências policiais contra ele ; VII - remeter , no prazo legal , os autos do inquérito policial ao juiz e ao Ministério Público . § 1o O pedido da ofendida será tomado a termo pela autoridade policial e deverá conter : I - qualificação da ofendida e do agressor ; II - nome e idade dos dependentes ; III - descrição sucinta do fato e das medidas protetivas solicitadas pela ofendida . § 2o A autoridade policial deverá anexar ao documento referido no § 1o o boletim de ocorrência e cópia de todos os documentos disponíveis em posse da ofendida . § 3o Serão admitidos como meios de prova os laudos ou prontuários médicos fornecidos por hospitais e postos de saúde . Art . 12-A . Os Estados e o Distrito Federal , na formulação de suas políticas e planos de atendimento à mulher em situação de violência doméstica e familiar , darão prioridade , no âmbito da Polícia Civil , à criação de Delegacias Especializadas de Atendimento à Mulher ( Deams ) , de Núcleos Investigativos de Feminicídio e de equipes especializadas para o atendimento e a investigação das violências graves contra a mulher . Art . 12-B . ( VETADO ) . ( Incluído pela Lei nº 13.505 , de 2017 ) § 1o ( VETADO ) . ( Incluído pela Lei nº 13.505 , de 2017 ) § 2o ( VETADO . ( Incluído pela Lei nº 13.505 , de 2017 ) § 3o A autoridade policial poderá requisitar os serviços públicos necessários à defesa da mulher em situação de violência doméstica e familiar e de seus dependentes . ( Incluído pela Lei nº 13.505 , de 2017 ) TÍTULO IV DOS PROCEDIMENTOS CAPÍTULO I DISPOSIÇÕES GERAIS Art . 13 . Ao processo , ao julgamento e à execução das causas cíveis e criminais decorrentes da prática de violência doméstica e familiar contra a mulher aplicar-se-ão as normas dos Códigos de Processo Penal e Processo Civil e da legislação específica relativa à criança , ao adolescente e ao idoso que não conflitarem com o estabelecido nesta Lei . Art . 14 . Os Juizados de Violência Doméstica e Familiar contra a Mulher , órgãos da Justiça Ordinária com competência cível e criminal , poderão ser criados pela União , no Distrito Federal e nos Territórios , e pelos Estados , para o processo , o julgamento e a execução das causas decorrentes da prática de violência doméstica e familiar contra a mulher . Parágrafo único . Os atos processuais poderão realizar-se em horário noturno , conforme dispuserem as normas de organização judiciária . Art . 15 . É competente , por opção da ofendida , para os processos cíveis regidos por esta Lei , o Juizado : I - do seu domicílio ou de sua residência ; II - do lugar do fato em que se baseou a demanda ; III - do domicílio do agressor . Art . 16 . Nas ações penais públicas condicionadas à representação da ofendida de que trata esta Lei , só será admitida a renúncia à representação perante o juiz , em audiência especialmente designada com tal finalidade , antes do recebimento da denúncia e ouvido o Ministério Público . Art . 17 . É vedada a aplicação , nos casos de violência doméstica e familiar contra a mulher , de penas de cesta básica ou outras de prestação pecuniária , bem como a substituição de pena que implique o pagamento isolado de multa . CAPÍTULO II DAS MEDIDAS PROTETIVAS DE URGÊNCIA Seção I Disposições Gerais Art . 18 . Recebido o expediente com o pedido da ofendida , caberá ao juiz , no prazo de 48 ( quarenta e oito ) horas : I - conhecer do expediente e do pedido e decidir sobre as medidas protetivas de urgência ; II - determinar o encaminhamento da ofendida ao órgão de assistência judiciária , quando for o caso ; III - comunicar ao Ministério Público para que adote as providências cabíveis . Art . 19 . As medidas protetivas de urgência poderão ser concedidas pelo juiz , a requerimento do Ministério Público ou a pedido da ofendida . § 1o As medidas protetivas de urgência poderão ser concedidas de imediato , independentemente de audiência das partes e de manifestação do Ministério Público , devendo este ser prontamente comunicado . § 2o As medidas protetivas de urgência serão aplicadas isolada ou cumulativamente , e poderão ser substituídas a qualquer tempo por outras de maior eficácia , sempre que os direitos reconhecidos nesta Lei forem ameaçados ou violados . § 3o Poderá o juiz , a requerimento do Ministério Público ou a pedido da ofendida , conceder novas medidas protetivas de urgência ou rever aquelas já concedidas , se entender necessário à proteção da ofendida , de seus familiares e de seu patrimônio , ouvido o Ministério Público . Art . 20 . Em qualquer fase do inquérito policial ou da instrução criminal , caberá a prisão preventiva do agressor , decretada pelo juiz , de ofício , a requerimento do Ministério Público ou mediante representação da autoridade policial . Parágrafo único . O juiz poderá revogar a prisão preventiva se , no curso do processo , verificar a falta de motivo para que subsista , bem como de novo decretá-la , se sobrevierem razões que a justifiquem . Art . 21 . A ofendida deverá ser notificada dos atos processuais relativos ao agressor , especialmente dos pertinentes ao ingresso e à saída da prisão , sem prejuízo da intimação do advogado constituído ou do defensor público . Parágrafo único . A ofendida não poderá entregar intimação ou notificação ao agressor . Seção II Das Medidas Protetivas de Urgência que Obrigam o Agressor Art . 22 . Constatada a prática de violência doméstica e familiar contra a mulher , nos termos desta Lei , o juiz poderá aplicar , de imediato , ao agressor , em conjunto ou separadamente , as seguintes medidas protetivas de urgência , entre outras : I - suspensão da posse ou restrição do porte de armas , com comunicação ao órgão competente , nos termos da Lei no 10.826 , de 22 de dezembro de 2003 ; II - afastamento do lar , domicílio ou local de convivência com a ofendida ; III - proibição de determinadas condutas , entre as quais : a ) aproximação da ofendida , de seus familiares e das testemunhas , fixando o limite mínimo de distância entre estes e o agressor ; b ) contato com a ofendida , seus familiares e testemunhas por qualquer meio de comunicação ; c ) freqüentação de determinados lugares a fim de preservar a integridade f

In [ ]:
def train_model_ner(dados_train, dados_validacao, epochs):
  model = spacy.load('pt_core_news_sm')
  if 'ner' not in model.pipe_names:
    ner = model.create_pipe('ner')
    model.add_pipe(ner, last=True)
  else:
    ner = model.get_pipe('ner')

  for _, anotacoes in dados_train:
    for ent in anotacoes.get('entities'):
      ner.add_label(ent[2])

  other_pipes = [pipe for pipe in model.pipe_names if pipe != 'ner']

  with model.disable_pipes(*other_pipes):
    spacy.util.fix_random_seed()
    optimizer = model.create_optimizer()

    for epoch in tqdm(range(epochs), desc = 'Treinando modelo'):
      random.seed(44)
      random.shuffle(dados_train)
      losses = {'ner': 0.0}

      for texts, anotacoes in dados_train:
        example = Example.from_dict(model.make_doc(texts), anotacoes)
        model.update([example], drop = 0.2, sgd=optimizer, losses=losses)

      print(f'\nEPOCH: {epoch+1} - LOSS médio de treino: {losses["ner"]/len(dados_train)}')

      val_losses = {'ner': 0.0}
      examples = []
      for texts, anotacoes in dados_validacao:
        example = Example.from_dict(model.make_doc(texts), anotacoes)
        examples.append(example)

      for example in examples:
        model.update(examples, drop=0, sgd=None, losses=val_losses)

      print(f'\nEPOCH: {epoch+1} - LOSS médio de treino: {val_losses["ner"]/len(dados_validacao)}')

  return model

Utilização de modelos pré-treinados:

1. Economia de tempo: treinar um modelo do zero exige muitos dados e tempo de processamento, enquanto os modelos pré-treinados já têm uma base pronta para uso.
2. Maior precisão: os modelos pré-treinados são ajustados com grandes volumes de dados, resultando em uma compreensão melhor das nuances do idioma.
3. Fácil customização: embora os modelos pré-treinados possam ser usados como estão, é possível ajustá-los para tarefas específicas (como NER em documentos jurídicos), adicionando novas entidades ou ajustando os parâmetros.

## Treinando e salvando modelo

In [ ]:
model_ner = train_model_ner(dados_train, dados_validacao, epochs = 30)

Treinando modelo:   0%|          | 0/30 [00:00<?, ?it/s]

EPOCH: 1 - LOSS médio de treino: 1001.248046875

Treinando modelo:   3%|▎         | 1/30 [01:43<50:07, 103.72s/it]

EPOCH: 1 - LOSS médio de treino: 7366.34912109375

EPOCH: 2 - LOSS médio de treino: 598.9879760742188

Treinando modelo:   7%|▋         | 2/30 [03:24<47:38, 102.08s/it]

EPOCH: 2 - LOSS médio de treino: 3481.00048828125

EPOCH: 3 - LOSS médio de treino: 422.7875061035156

Treinando modelo:  10%|█         | 3/30 [05:14<47:33, 105.69s/it]

EPOCH: 3 - LOSS médio de treino: 1851.306884765625

EPOCH: 4 - LOSS médio de treino: 338.8021545410156

Treinando modelo:  13%|█▎        | 4/30 [06:55<44:59, 103.83s/it]

EPOCH: 4 - LOSS médio de treino: 1066.5037841796875

EPOCH: 5 - LOSS médio de treino: 280.25286865234375

Treinando modelo:  17%|█▋        | 5/30 [08:41<43:36, 104.66s/it]

EPOCH: 5 - LOSS médio de treino: 608.1807861328125

EPOCH: 6 - LOSS médio de treino: 219.34304809570312

Treinando modelo:  20%|██        | 6/30 [10:34<43:00, 107.53s/it]

EPOCH: 6 - LOSS médio de treino: 345.887451171875

EPOCH: 7 - LOSS médio de treino: 213.6973114013672

Treinando modelo:  23%|██▎       | 7/30 [12:30<42:11, 110.07s/it]

EPOCH: 7 - LOSS médio de treino: 285.38653564453125

EPOCH: 8 - LOSS médio de treino: 176.20228576660156

Treinando modelo:  27%|██▋       | 8/30 [14:11<39:20, 107.32s/it]

EPOCH: 8 - LOSS médio de treino: 239.81008911132812

EPOCH: 9 - LOSS médio de treino: 151.27195739746094

Treinando modelo:  30%|███       | 9/30 [15:59<37:37, 107.51s/it]

EPOCH: 9 - LOSS médio de treino: 167.42031860351562

EPOCH: 10 - LOSS médio de treino: 135.41549682617188

Treinando modelo:  33%|███▎      | 10/30 [17:45<35:39, 107.00s/it]

EPOCH: 10 - LOSS médio de treino: 144.28631591796875

EPOCH: 11 - LOSS médio de treino: 126.79148864746094

Treinando modelo:  37%|███▋      | 11/30 [19:29<33:36, 106.11s/it]

EPOCH: 11 - LOSS médio de treino: 120.62770080566406

EPOCH: 12 - LOSS médio de treino: 119.4058609008789

Treinando modelo:  40%|████      | 12/30 [21:10<31:22, 104.59s/it]

EPOCH: 12 - LOSS médio de treino: 130.69473266601562

EPOCH: 13 - LOSS médio de treino: 105.6749496459961

Treinando modelo:  43%|████▎     | 13/30 [22:51<29:20, 103.54s/it]

EPOCH: 13 - LOSS médio de treino: 97.76325988769531

EPOCH: 14 - LOSS médio de treino: 99.94837951660156

Treinando modelo:  47%|████▋     | 14/30 [24:53<29:04, 109.06s/it]

EPOCH: 14 - LOSS médio de treino: 87.54251098632812

EPOCH: 15 - LOSS médio de treino: 90.39610290527344

Treinando modelo:  50%|█████     | 15/30 [26:36<26:46, 107.11s/it]

EPOCH: 15 - LOSS médio de treino: 114.72562408447266

EPOCH: 16 - LOSS médio de treino: 87.61642456054688

Treinando modelo:  53%|█████▎    | 16/30 [28:20<24:48, 106.31s/it]

EPOCH: 16 - LOSS médio de treino: 116.10472106933594

EPOCH: 17 - LOSS médio de treino: 85.88056182861328

Treinando modelo:  57%|█████▋    | 17/30 [30:02<22:44, 104.93s/it]

EPOCH: 17 - LOSS médio de treino: 89.77884674072266

EPOCH: 18 - LOSS médio de treino: 80.46653747558594

Treinando modelo:  60%|██████    | 18/30 [31:43<20:45, 103.77s/it]

EPOCH: 18 - LOSS médio de treino: 81.94644165039062

EPOCH: 19 - LOSS médio de treino: 78.87139892578125

Treinando modelo:  63%|██████▎   | 19/30 [33:23<18:49, 102.64s/it]

EPOCH: 19 - LOSS médio de treino: 91.81954956054688

EPOCH: 20 - LOSS médio de treino: 71.25712585449219

Treinando modelo:  67%|██████▋   | 20/30 [35:03<16:59, 101.96s/it]

EPOCH: 20 - LOSS médio de treino: 92.34671020507812

EPOCH: 21 - LOSS médio de treino: 66.04156494140625

Treinando modelo:  70%|███████   | 21/30 [36:44<15:14, 101.62s/it]

EPOCH: 21 - LOSS médio de treino: 107.679443359375

EPOCH: 22 - LOSS médio de treino: 64.98296356201172

Treinando modelo:  73%|███████▎  | 22/30 [38:24<13:28, 101.05s/it]

EPOCH: 22 - LOSS médio de treino: 73.83940887451172

EPOCH: 23 - LOSS médio de treino: 61.00129318237305

Treinando modelo:  77%|███████▋  | 23/30 [40:22<12:24, 106.31s/it]

EPOCH: 23 - LOSS médio de treino: 78.8326187133789

EPOCH: 24 - LOSS médio de treino: 55.240013122558594

Treinando modelo:  80%|████████  | 24/30 [42:12<10:44, 107.41s/it]

EPOCH: 24 - LOSS médio de treino: 69.34977722167969

EPOCH: 25 - LOSS médio de treino: 61.15325164794922

Treinando modelo:  83%|████████▎ | 25/30 [43:53<08:46, 105.29s/it]

EPOCH: 25 - LOSS médio de treino: 72.6269302368164

EPOCH: 26 - LOSS médio de treino: 55.2753791809082

Treinando modelo:  87%|████████▋ | 26/30 [45:32<06:54, 103.60s/it]

EPOCH: 26 - LOSS médio de treino: 72.09188079833984

EPOCH: 27 - LOSS médio de treino: 51.146705627441406

Treinando modelo:  90%|█████████ | 27/30 [47:12<05:07, 102.53s/it]

EPOCH: 27 - LOSS médio de treino: 72.55899047851562

EPOCH: 28 - LOSS médio de treino: 49.809165954589844

Treinando modelo:  93%|█████████▎| 28/30 [48:52<03:23, 101.59s/it]

EPOCH: 28 - LOSS médio de treino: 77.51719665527344

EPOCH: 29 - LOSS médio de treino: 46.893821716308594

Treinando modelo:  97%|█████████▋| 29/30 [50:32<01:41, 101.22s/it]

EPOCH: 29 - LOSS médio de treino: 67.18702697753906

EPOCH: 30 - LOSS médio de treino: 45.55202102661133

Treinando modelo: 100%|██████████| 30/30 [52:12<00:00, 104.41s/it]

EPOCH: 30 - LOSS médio de treino: 74.9092788696289

In [ ]:
model_ner.to_disk('model_ner')

### Salvando e carregando modelo

In [ ]:
model_ner = spacy.load('/content/model_ner')

In [ ]:
!zip -r model_ner.zip '/content/model_ner'

  adding: content/model_ner/ (stored 0%)
  adding: content/model_ner/tokenizer (deflated 84%)
  adding: content/model_ner/senter/ (stored 0%)
  adding: content/model_ner/senter/cfg (stored 0%)
  adding: content/model_ner/senter/model (deflated 10%)
  adding: content/model_ner/lemmatizer/ (stored 0%)
  adding: content/model_ner/lemmatizer/cfg (deflated 76%)
  adding: content/model_ner/lemmatizer/trees (deflated 80%)
  adding: content/model_ner/lemmatizer/model (deflated 7%)
  adding: content/model_ner/morphologizer/ (stored 0%)
  adding: content/model_ner/morphologizer/cfg (deflated 92%)
  adding: content/model_ner/morphologizer/model (deflated 7%)
  adding: content/model_ner/config.cfg (deflated 74%)
  adding: content/model_ner/meta.json (deflated 87%)
  adding: content/model_ner/ner/ (stored 0%)
  adding: content/model_ner/ner/cfg (deflated 33%)
  adding: content/model_ner/ner/moves (deflated 80%)
  adding: content/model_ner/ner/model (deflated 7%)
  adding: content/model_ner/parser/ (stored 0%)
  adding: content/model_ner/parser/cfg (deflated 32%)
  adding: content/model_ner/parser/moves (deflated 52%)
  adding: content/model_ner/parser/model (deflated 7%)
  adding: content/model_ner/vocab/ (stored 0%)
  adding: content/model_ner/vocab/strings.json (deflated 78%)
  adding: content/model_ner/vocab/vectors.cfg (stored 0%)
  adding: content/model_ner/vocab/lookups.bin (stored 0%)
  adding: content/model_ner/vocab/key2row (stored 0%)
  adding: content/model_ner/vocab/vectors (deflated 45%)
  adding: content/model_ner/attribute_ruler/ (stored 0%)
  adding: content/model_ner/attribute_ruler/patterns (deflated 76%)
  adding: content/model_ner/tok2vec/ (stored 0%)
  adding: content/model_ner/tok2vec/cfg (stored 0%)
  adding: content/model_ner/tok2vec/model (deflated 7%)

In [ ]:
import requests

url = 'https://cdn3.gnarususercontent.com.br/3972-nlp/Projeto/dados/20150110436469APC.txt'
resposta = requests.get(url)

with open('20150110436469APC.txt', 'w', encoding='utf-8') as f:
    f.write(resposta.text)

In [ ]:
with open('/content/20150110436469APC.txt', encoding='utf-8') as f:
  text = f.read()

In [ ]:
print(text)

E M E N T A
Poder JudiciÃ¡rio da UniÃ£o
TRIBUNAL DE JUSTIÃA DO DISTRITO FEDERAL E TERRITÃRIOS Fls. _____
ÃrgÃ£o : 8Âª TURMA CÃVEL
Classe : APELAÃÃO CÃVEL
N. Processo : 20150110436469APC
(0012843-03.2015.8.07.0001)
Apelante(s) : BRASILIA CURSOS E CONCURSOS LTDA
GRANCURSOS ESCOLA PARA
CONCURSOS PUBLICOS LTDA
Apelado(s) : ALISSON SILVA BATISTA DE MORAES
Relatora : Desembargadora NÃDIA CORRÃA LIMA
AcÃ³rdÃ£o N. : 1082726
CIVIL E PROCESSUAL CIVIL. AÃÃO MONITÃRIA. CITAÃÃO
REALIZADA APÃS O DECURSO DO PRAZO
PRESCRICIONAL. PRESCRIÃÃO DA PRETENSÃO
MONITÃRIA. RECONHECIMENTO. MANUTENÃÃO DA
SENTENÃA.
1. Nos termos da SÃºmula nÂº 503 do colendo Superior Tribunal
de JustiÃ§a, "O prazo para ajuizamento de aÃ§Ã£o monitÃ³ria em
face do emitente de cheque sem forÃ§a executiva Ã© quinquenal,
a contar do dia seguinte Ã  data de emissÃ£o estampada na
cÃ¡rtula".
2. Evidenciado que a citaÃ§Ã£o somente foi aperfeiÃ§oada apÃ³s o
decurso do prazo prescricional, tem-se por correta a extinÃ§Ã£o
da demanda monitÃ³ria, com resoluÃ§Ã£o do mÃ©rito, nos termos do
artigo 485, inciso II, do CÃ³digo de Processo Civil.
3. Recurso de ApelaÃ§Ã£o conhecido e nÃ£o provido.
CÃ³digo de VerificaÃ§Ã£o :2018ACOIJG91GM498IVMWX8ID8A
GABINETE DA DESEMBARGADORA NÃDIA CORRÃA LIMA 1
Fls. _____
ApelaÃ§Ã£o CÃ­vel 20150110436469APC
A C Ã R D Ã O
Acordam os Senhores Desembargadores da 8Âª TURMA CÃVEL do
Tribunal de JustiÃ§a do Distrito Federal e TerritÃ³rios, NÃDIA CORRÃA LIMA -
Relatora, DIAULAS COSTA RIBEIRO - 1Âº Vogal, EUSTÃQUIO DE CASTRO - 2Âº
Vogal, sob a presidÃªncia do Senhor Desembargador DIAULAS COSTA RIBEIRO,
em proferir a seguinte decisÃ£o: RECURSO DE APELAÃÃO CONHECIDO E NÃO
PROVIDO. UNÃNIME., de acordo com a ata do julgamento e notas taquigrÃ¡ficas.
Brasilia(DF), 15 de MarÃ§o de 2018.
Documento Assinado Eletronicamente
NÃDIA CORRÃA LIMA
Relatora
CÃ³digo de VerificaÃ§Ã£o :2018ACOIJG91GM498IVMWX8ID8A
GABINETE DA DESEMBARGADORA NÃDIA CORRÃA LIMA 2

Trata-se de aÃ§Ã£o monitÃ³ria ajuizada por BRASILIA CURSOS E
CONCURSOS LTDA GRANCURSOS ESCOLA PARA
CONCURSOS PUBLICOS LTDA em desfavor de ALISSON
SILVA BATISTA DE MORAES, partes qualificadas nos autos.
Alega o autor que Ã© credor do rÃ©u da importÃ¢ncia representada
por duas cÃ¡rtulas de cheques do Banco Real, no valor de R$
175,50 cada cÃ¡rtula, atualizado atÃ© 30/03/2015 em R$ 469,24.
Requer a citaÃ§Ã£o do rÃ©u para que pague a importÃ¢ncia de R$
469,24 (quatrocentos e sessenta e nove reais e vinte e quatro
centavos), acrescida de atualizaÃ§Ã£o e juros devidos, ou para
que ofereÃ§a embargos, sob pena de ser convertido o mandado
inicial em mandado executivo. Junta os documentos de fls.
04/10.
ApÃ³s diversas tentativas infrutÃ­feras de citaÃ§Ã£o pessoal, o rÃ©u
foi citado por edital (fls. 80/81), mas deixou transcorrer "in albis"
o prazo para defesa, conforme fl. 84. A Curadoria Especial
ofertou embargos Ã  aÃ§Ã£o monitÃ³ria, por negativa geral (fl. 85).
ManifestaÃ§Ã£o do autor/embargado as fls. 89/90.
Intimadas as partes a respeito de eventual prescriÃ§Ã£o,
manifestaram-se as fls. 98/103 e 104-verso.

 Acrescento que o d Magistrado sentenciante reconheceu a
prescriÃ§Ã£o da pretensÃ£o monitÃ³ria e, com fundamento no artigo 487, inciso II, do
CÃ³digo de Processo Civil, extinguiu o processo, com resoluÃ§Ã£o do mÃ©rito,
condenando a parte autora ao pagamento das custas judiciais e dos honorÃ¡rios
advocatÃ­cios, estes fixados em 10% (dez por cento) do valor da causa.
Fls. _____
ApelaÃ§Ã£o CÃ­vel 20150110436469APC
R E L A T Ã R I O
 Cuida-se de ApelaÃ§Ã£o CÃ­vel interposta por BRASÃLIA CURSOS E
CONCURSOS LTDA em face da r. sentenÃ§a de fls. 105/107, cujo relatÃ³rio
transcrevo, in verbis:
CÃ³digo de VerificaÃ§Ã£o :2018ACOIJG91GM498IVMWX8ID8A
GABINETE DA DESEMBARGADORA NÃDIA CORRÃA LIMA 3
 Inconformado, o autor interpÃ´s recurso de apelaÃ§Ã£o Ã s fls. 203/205,
afirmando haver envidado todos os esforÃ§os para localizar o endereÃ§o do rÃ©u, sem,
contudo, ter logrado Ãªxito, razÃ£o pela qual promoveu a citaÃ§Ã£o por edital.
 Ao final, o autor alegou que nÃ£o estaria configurada a prescriÃ§Ã£o da
pretensÃ£o monitÃ³ria, razÃ£o pela qual postulou a reforma da r. sentenÃ§a, para que
seja dado regular processamento do feito.
 Preparo regular (fl. 116).
 ContrarrazÃµes ofertadas Ã  fl. 117-v.
 Ã o relatÃ³rio.
Fls. _____
ApelaÃ§Ã£o CÃ­vel 20150110436469APC
CÃ³digo de VerificaÃ§Ã£o :2018ACOIJG91GM498IVMWX8ID8A
GABINETE DA DESEMBARGADORA NÃDIA CORRÃA LIMA 4
Cuida-se de ApelaÃ§Ã£o CÃ­vel interposta por BRASÃLIA CURSOS E
CONCURSOS LTDA em face da r. sentenÃ§a de fls. 105/107, pela qual o d.
Magistrado de primeiro grau, com fundamento no artigo 487, inciso II, do CÃ³digo de
Processo Civil, julgou extinta a AÃ§Ã£o MonitÃ³ria proposta em desfavor de ALISSON
SILVA BATISTA DE MORAES, ante o reconhecimento da prescriÃ§Ã£o da pretensÃ£o
deduzida na inicial.
Em suas razÃµes de apelo, a autora afirmou que nÃ£o poderia ter sido
reconhecida aprescriÃ§Ã£o da pretensÃ£o monitÃ³ria, uma vez que a nÃ£o localizaÃ§Ã£o do
apelado no prazo estipulado em lei nÃ£o lhe pode ser imputada, porquanto adotou
diversas medidas com a finalidade de promover a citaÃ§Ã£o do rÃ©u.
Ã a suma dos fatos.
Da anÃ¡lise dos autos, tenho que o inconformismo manifestado pela
autora nÃ£o merece prosperar.
Nos termos da SÃºmula nÂº 503 do colendo Superior Tribunal de
JustiÃ§a, "O prazo para ajuizamento de aÃ§Ã£o monitÃ³ria em face do emitente de
cheque sem forÃ§a executiva Ã© quinquenal, a contar do dia seguinte Ã  data de
emissÃ£o estampada na cÃ¡rtula".
Cabe ressaltar que, segundo o artigo 202, inciso I, do CÃ³digo Civil, a
interrupÃ§Ã£o da prescriÃ§Ã£o, que somente poderÃ¡ ocorrer uma vez, dar-se-Ã¡ "por
despacho do juiz, mesmo incompetente, que ordenar a citaÃ§Ã£o, se o interessado a
promover no prazo e na forma da lei processual."
Ressalte-se que, de acordo com o artigo 240, Â§Â§ 1Âº e 2Âº, do CÃ³digo
de Processo Civil, incumbe ao autor da aÃ§Ã£o, no prazo de 10 (dez) dias, viabilizar a
citaÃ§Ã£o do rÃ©u, sob pena de nÃ£o ver interrompida a prescriÃ§Ã£o no momento do
ajuizamento, mas apenas na data em que efetivamente for realizado o ato citatÃ³rio.
Neste sentido:
No mesmo sentido cito a jurisprudÃªncia deste e. Tribunal de JustiÃ§a,
in verbis:
Fls. _____
ApelaÃ§Ã£o CÃ­vel 20150110436469APC
V O T O S
A Senhora Desembargadora NÃDIA CORRÃA LIMA - Relatora
ConheÃ§o do recurso, porquanto presentes os pressupostos de
admissibilidade.
CÃ³digo de VerificaÃ§Ã£o :2018ACOIJG91GM498IVMWX8ID8A
GABINETE DA DESEMBARGADORA NÃDIA CORRÃA LIMA 5
CIVIL E PROCESSUAL CIVIL. APELAÃÃO CÃVEL.
EXECUÃÃO EXTRAJUDICIAL. CÃDULA DE CRÃDITO
BANCÃRIO. PRESCRIÃÃO TRIENAL. CITAÃÃO POR EDITAL
REALIZADA QUANDO PASSADOS MAIS DE OITO ANOS DO
TERMO INICIAL DO PRAZO PRESCRICIONAL DA
PRETENSÃO EXECUTÃRIA. CONSUMAÃÃO DA
PRESCRIÃÃO. 1. A prescriÃ§Ã£o da pretensÃ£o executÃ³ria
fundada em cÃ©dula de crÃ©dito bancÃ¡rio Ã© sujeita ao prazo
trienal, consoante o disposto no art. 44, da Lei n.Âº 10.931/2004.
2. Em que pese o disposto no art. 202, inciso I, do CC, elencar
como causa interruptiva da prescriÃ§Ã£o o despacho do juiz que
determina a citaÃ§Ã£o, esse preceito legal deve ser interpretado
em conjunto com a exigÃªncia de que o autor promova o ato
citatÃ³rio no prazo e na forma da lei processual, isto Ã©, em
observÃ¢ncia ao disposto no art. 240, Â§ 2Âº, do CPC. 3. Nos
termos do Â§ 2Âº do art. 240 do CPC, incumbe Ã  parte autora
promover a citaÃ§Ã£o do rÃ©u no prazo de dez (10) dias. Com
efeito, embora referido prazo nÃ£o seja peremptÃ³rio, vale
notar que a citaÃ§Ã£o levada a efeito apÃ³s o transcurso
deste, nÃ£o tem o condÃ£o de interromper a prescriÃ§Ã£o,
retroagindo Ã  data da propositura da aÃ§Ã£o (Â§ 1Âº do art. 240,
do CPC), salvo se a demora na citaÃ§Ã£o se der por motivos
inerentes ao mecanismo da JustiÃ§a, consoante o Â§ 3Âº do
mesmo artigo do CPC e o Enunciado nÂº 106, do STJ, que
nÃ£o Ã© o caso. 4. Feita a citaÃ§Ã£o editalÃ­cia quando passados
mais de oito (08) anos do inÃ­cio do curso do prazo prescricional,
sem que se verifique, em data anterior, a ocorrÃªncia de
qualquer outra causa interruptiva ou suspensiva do prazo
prescricional, impÃµe-se o reconhecimento da prescriÃ§Ã£o. 5.
Recurso nÃ£o provido. SentenÃ§a mantida. (AcÃ³rdÃ£o n.999404,
20160610082800APC, Relator: ARNOLDO CAMANHO 4Âª
TURMA CÃVEL, Data de Julgamento: 22/02/2017, Publicado no
DJE: 08/03/2017. PÃ¡g.: 283/300) - grifo nosso.
Fls. _____
ApelaÃ§Ã£o CÃ­vel 20150110436469APC
CÃ³digo de VerificaÃ§Ã£o :2018ACOIJG91GM498IVMWX8ID8A
GABINETE DA DESEMBARGADORA NÃDIA CORRÃA LIMA 6
Compulsando os autos, verifica-se que as cÃ¡rtulas de cheques foram
emitidas em 20/08/2010 e 20/09/2010 (fl. 9) e a AÃ§Ã£o MonitÃ³ria foi ajuizada em
20/04/2015.
Cabe ressaltar que muito embora a demanda tenha sido ajuizada
ainda dentro do prazo prescricional a parte autora nÃ£o logrou promover a citaÃ§Ã£o do
rÃ©u dentro do prazo prescricional, sendo que a citaÃ§Ã£o deste somente veio a ocorrer
em 01/08/2016, na modalidade editalÃ­cia (fls. 80/81), quando jÃ¡ se encontrava
exaurido o prazo prescricional.
Percebe-se, assim, que entre o despacho inicial positivo, exarado
em 22/04/2015, e a efetivaÃ§Ã£o do ato citatÃ³rio, ocorrido em 01/08/2016, decorreu,
aproximadamente, um ano e seis meses, nÃ£o se podendo falar, neste caso
especÃ­fico, em retroaÃ§Ã£o da interrupÃ§Ã£o do lapso prescricional Ã  data da propositura
da demanda.
Portanto, tenho por incensurÃ¡vel a r. sentenÃ§a recorrida, ao
reconhecer a prescriÃ§Ã£o da pretensÃ£o monitÃ³ria.
Pelas razÃµes expostas, NEGO PROVIMENTO AO RECURSO DE
APELAÃÃO e mantenho Ã­ntegra a r. sentenÃ§a.
Ã como voto.
Fls. _____
ApelaÃ§Ã£o CÃ­vel 20150110436469APC
O Senhor Desembargador DIAULAS COSTA RIBEIRO - Vogal
Com o relator
O Senhor Desembargador EUSTÃQUIO DE CASTRO - Vogal
Com o relator
 D E C I S Ã O
Recurso de ApelaÃ§Ã£o conhecido e nÃ£o provido. UnÃ¢nime.
CÃ³digo de VerificaÃ§Ã£o :2018ACOIJG91GM498IVMWX8ID8A
GABINETE DA DESEMBARGADORA NÃDIA CORRÃA LIMA 7

In [ ]:
!unzip model_ner.zip -d '/content/model_ner'

In [ ]:
doc = model_ner(text)

spacy.displacy.render(doc, style = 'ent', jupyter = True)

In [ ]:
rotulos = list(model_ner.get_pipe('ner').labels)
rotulos

In [ ]:
cores = {
 'B-JURISPRUDENCIA': '#F0F8FF',
 'B-LEGISLACAO': '#FA8072',
 'B-LOCAL': '#98FB98',
 'B-ORGANIZACAO': '#DDA0DD',
 'B-PESSOA': '#F0E68C',
 'B-TEMPO': '#FFB6C1',
 'I-JURISPRUDENCIA': '#F0F8FF',
 'I-LEGISLACAO': '#FA8072',
 'I-LOCAL': '#98FB98',
 'I-ORGANIZACAO': '#DDA0DD',
 'I-PESSOA': '#F0E68C',
 'I-TEMPO': '#FFB6C1',
 'LOC': '#D3D3D3',
 'MISC': '#D3D3D3',
 'ORG': '#D3D3D3',
 'PER': '#D3D3D3'
}
opcoes = {'ents': rotulos, 'colors': cores}

spacy.displacy.render(doc, style = 'ent', jupyter = True, options = opcoes)

## Pontos importantes


- Realizar a leitura de arquivos de texto a partir de um arquivo compactado;
- Entender o conceito do reconhecimento de entidades nomeadas e exemplos de aplicações;
- Fazer o download e aplicar um modelo NER da biblioteca SpaCy;
- Listar e tabelar todas as entidades nomeadas de um documento usando oSpaCy;
- Destacar entidades nomeadas em um texto a partir de um método de renderização do Displacy;
- Realizar a tokenização de textos e armazenar o resultado em uma tabela;
- Rotular dados para o reconhecimento de entidades nomeadas no formato IOB;
- Transformar os dados para o formato adequado, com o texto dos documentos e posição das entidades no texto;
- Realizar o processo de divisão dos dados de treinamento e validação;
- Configurar o pipeline de um modelo NER em uma função de treinamento;
- Criar o loop de treinamento e validação para um modelo de NLP;
- Utilizar modelos pré-treinados e aprimorar sua aplicação com novos dados.
Realizar o treinamento de um modelo de NLP;
- Armazenar o modelo em um arquivo compactado para ser utilizado fora do ambiente do Google Collaboratory;
- Carregar o modelo treinado usando a biblioteca SpaCy;
- Testar o funcionamento do modelo em um novo documento para identificar entidades nomeadas;
- Alterar as cores da renderização do DisplaCy para destacar as entidades nomeadas reconhecidas;
- Preparar o ambiente virtual com as bibliotecas necessárias para utilização do Streamlit;
- Criar uma aplicação interativa utilizando o Streamlit;
- Realizar o reconhecimento de entidades nomeadas de forma simples a partir do upload de arquivos de texto;
- Utilizar a renderização do Spacy no ambiente do Streamlit para destacar entidades nomeadas diretamente no texto;